#!/usr/bin/env python

import os
import sys

oldcwd = os.getcwd();
os.chdir(os.path.dirname(sys.argv[0]));
basedir = os.getcwd();
os.chdir(oldcwd);

sys.path.insert(0, basedir)

import javascriptlint
javascriptlint.main()
