#!/bin/bash

# All tests must pass!
set -o errexit

if [[ $(uname -s) != 'SunOS' ]]; then
    echo "FATAL: this can only run on SmartOS"
    exit 1
fi

if [[ $(zonename) != 'global' ]]; then
    echo "FATAL: this can only run in the GZ"
    exit 1
fi

if [[ $(id -u) != 0 ]]; then
    echo "FATAL: this can only run as root"
    exit 1
fi

export TAP=1
# ./node-tap/bin/tap doesn't work.
for test in $(ls $(pwd)/tests/); do
    node $(pwd)/tests/${test}
done

exit 0
