#!/bin/bash

# All tests must pass!
set -o errexit

start_time=$(date +%s)

if [[ $(uname -s) != 'SunOS' ]]; then
    echo "FATAL: this can only run on SmartOS"
    exit 1
fi

if [[ $(zonename) != 'global' ]]; then
    echo "FATAL: this can only run in the GZ"
    exit 1
fi

if [[ $(id -u) != 0 ]]; then
    echo "FATAL: this can only run as root"
    exit 1
fi

for test in $(ls $(pwd)/tests/); do
    /usr/vm/test/run-test $(pwd)/tests/${test} | tee -a /tmp/test.output.$$
done

end_time=$(date +%s)
elapsed=$((${end_time} - ${start_time}))

tests=$(grep "^# tests [0-9]" /tmp/test.output.$$ | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
passed=$(grep "^# pass  [0-9]" /tmp/test.output.$$ | tr -s ' ' | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)

[[ -z ${tests} ]] && tests=0
[[ -z ${passed} ]] && passed=0

fail=$((${tests} - ${passed}))

echo ""
echo "TESTS COMPLETE IN ${elapsed} SECONDS, SUMMARY:"
echo ""
echo -e '\E[32;40m'"PASS: ${passed} / ${tests}"; tput sgr0
if [[ ${fail} -gt 0 ]]; then
    echo -e '\E[31;40m'"FAIL: ${fail} / ${tests}"; tput sgr0
fi
echo ""

exit 0
