#!/bin/bash

# All tests must pass!
set -o errexit

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ ! -f "/lib/sdc/.sdc-test-no-production-data" ]]; then
    cat <<EOF
To run this test you must create the file:

    /lib/sdc/.sdc-test-no-production-data

after ensuring you have no production data on this machine.
EOF
    exit 2
fi

start_time=$(date +%s)

if [[ $(uname -s) != 'SunOS' ]]; then
    echo "FATAL: this can only run on SmartOS"
    exit 1
fi

if [[ $(zonename) != 'global' ]]; then
    echo "FATAL: this can only run in the GZ"
    exit 1
fi

if [[ $(id -u) != 0 ]]; then
    echo "FATAL: this can only run as root"
    exit 1
fi

if [[ -z "$1" ]]; then
    echo "FATAL: no test file specified"
    exit 1
fi

# Before starting tests, ensure we have the source(s) we want for test VM images

have_sources="imgadm sources | sort"
want_source="grep IMAGES_SOURCE ${ROOT}/common/vmtest.js | cut -d\' -f2"

for src in $(comm -1 -3 <(eval ${have_sources}) <(eval ${want_source})); do
    imgadm sources -a "${src}"
done

# Ensure images used by tests are installed

installed_images='imgadm list -H -o uuid | sort'
want_images="cat ${ROOT}/common/vmtest.js | grep exports\.CURRENT_.*_UUID \
    | grep -v "process.env" | cut -d \"'\" -f2 | sort"

for img in $(comm -1 -3 <(eval ${installed_images}) <(eval ${want_images})); do
    if [[ ${img} == "71101322-43a5-11e1-8f01-cf2a3031a7f4" ]]; then
        MANTA_PATH="https://us-east.manta.joyent.com/Joyent_Dev/public/old_images/ubuntu-10.04"
        (cd /var/tmp && curl -kO ${MANTA_PATH}/${img}.file \
            && curl -kO ${MANTA_PATH}/${img}.manifest \
            && imgadm install -f ${img}.file -m ${img}.manifest \
            && rm -f ${img}.file ${img}.manifest)
    elif [[ ${img} == "01b2c898-945f-11e1-a523-af1afbe22822" ]]; then
        MANTA_PATH="https://us-east.manta.joyent.com/Joyent_Dev/public/old_images/smartos-1.6.3"
        (cd /var/tmp && curl -kO ${MANTA_PATH}/${img}.file \
            && curl -kO ${MANTA_PATH}/${img}.manifest \
            && imgadm install -f ${img}.file -m ${img}.manifest \
            && rm -f ${img}.file ${img}.manifest)
    else
        imgadm import "${img}"
    fi
done

# Special case for docker

imgadm sources --add-docker-hub
export DOCKER_BASE_IMAGE_UUID=$(imgadm list -o uuid,tags \
    | grep "\"docker:repo\":\"busybox\"" \
    | cut -d' ' -f1 \
    | head -1)
if [[ -z ${DOCKER_BASE_IMAGE_UUID} ]]; then
    imgadm import busybox:1.24.0
    export DOCKER_BASE_IMAGE_UUID=$(imgadm list -o uuid,tags \
        | grep "\"docker:repo\":\"busybox\"" \
        | cut -d' ' -f1)
    if [[ -z ${DOCKER_BASE_IMAGE_UUID} ]]; then
        echo "Unable to download busybox:1.24.0 docker image" >&2
        exit 1
    fi
fi

# Ensure nic tags needed by tests exist

for tag in admin external; do
    if ! /usr/bin/nictagadm exists ${tag} >/dev/null 2>&1; then
        echo "Missing NIC tag: ${tag}, please add w/ nictagadm and try again" >&2
        exit 2
    fi
done

set +o errexit
set -o pipefail
/usr/bin/ctrun -l child -o noorphan /usr/node/bin/node \
    --abort_on_uncaught_exception \
    /usr/vm/node_modules/nodeunit/bin/nodeunit \
    --reporter tap $1 | tee -a /tmp/test.output.$$
TEST_EXIT_CODE=$?
set +o pipefail
set -o errexit

end_time=$(date +%s)
elapsed=$((${end_time} - ${start_time}))

tests=$(grep "^# tests [0-9]" /tmp/test.output.$$ | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
passed=$(grep "^# pass  [0-9]" /tmp/test.output.$$ | tr -s ' ' | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
skipped=$(grep "^# skip  [0-9]" /tmp/test.output.$$ | tr -s ' ' | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)

[[ -z ${tests} ]] && tests=0
[[ -z ${passed} ]] && passed=0
[[ -z ${skipped} ]] && skipped=0

fail=$((${tests} - ${passed} - ${skipped}))

if [[ ${TEST_EXIT_CODE} != 0 ]]; then
    fail=$((${fail} + 1))
    tests="?"
fi

if [[ -t 0 ]]; then
    # We're on a terminal so output the summary
    echo "#"
    echo "# $1 TEST COMPLETE IN ${elapsed} SECONDS, SUMMARY:"
    echo "#"
    if [[ ${tests} != "?" ]]; then
        echo -e "# \033[32mPASS: ${passed} / ${tests}\033[39m"
    fi
    if [[ ${skipped} -gt 0 ]]; then
        echo -e "# \033[31mSKIP: ${skipped} / ${tests}\033[39m"
    fi
    if [[ ${fail} -gt 0 ]]; then
        echo -e "# \033[31mFAIL: ${fail} / ${tests}\033[39m"
    fi
    echo "#"
fi

if [[ ${fail} -gt 0 ]]; then
    exit 1
fi

exit 0
