#!/usr/node/bin/node
/*
 * Copyright (c) 2013, Joyent, Inc. All rights reserved.
 *
 * imgadm -- manage images on SmartOS
 */

var format = require('util').format;
var CLI = require('../lib/cli');


// ---- globals

var NAME = 'imgadm';


// ---- support stuff

function logerror(err, verbose) {
    if (err.code) {
        console.error(format('%s: error (%s): %s', NAME, err.code,
            err.message));
    } else {
        console.error(format('%s: error: %s', NAME, err.message));
    }
    if (verbose && err.stack) {
        console.error('\n' + err.stack);
    }
}


// ---- mainline

function main(argv) {
    var cli = new CLI();
    cli.main(argv, function (err, verbose) {
        if (err) {
            logerror(err, verbose);
            process.exit(err.exitStatus || 1);
        }
        process.exit(0);
    });
}

if (require.main === module) {
    main(process.argv);
}
