#!/usr/node/bin/node --abort_on_uncaught_exception
/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License, Version 1.0 only
 * (the "License").  You may not use this file except in compliance
 * with the License.
 *
 * You can obtain a copy of the license at http://smartos.org/CDDL
 *
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file.
 *
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 *
 * Copyright (c) 2013, Joyent, Inc. All rights reserved.
 *
 * * *
 * imgadm -- manage images on SmartOS
 */

var onlyif = require('/usr/node/node_modules/onlyif');
var CLI = require('../lib/cli');


function main(argv) {
    onlyif.rootInSmartosGlobal(function (onlyifErr) {
        if (onlyifErr) {
            console.error('imgadm: error: cannot run: ' + onlyifErr);
            process.exit(2);
        }
        var cli = new CLI();
        cli.main(argv, {}, function (err) {
            if (err) {
                process.exit(err.exitStatus || 1);
            } else {
                process.exit(0);
            }
        });
    });
}

if (require.main === module) {
    main(process.argv);
}
