#!/bin/bash

rdmnt=$1
copy_in=$2
if [ -z "${rdmnt}" ] || [ -z "${copy_in}" ]; then
  echo "Usage: $0 <root directory> <copy_in directory>"
  exit 1
fi

echo "Customizing ${rdmnt}"
pfexec cp /dev/null ${rdmnt}/etc/mnttab
pfexec cp /dev/null ${rdmnt}/var/log/syslog
pfexec cp /dev/null ${rdmnt}/var/adm/wtmpx
pfexec chown root:root ${rdmnt}
TZ=UTC date "+%Y-%m-%dT%H:%M:%SZ" | pfexec tee ${rdmnt}/etc/joyent_buildstamp >/dev/null 2>&1

# Setup the SMF repository + initial manifests
pfexec cp /dev/null ${rdmnt}/etc/svc/repository.db
pfexec /usr/sbin/svccfg -v repository ${rdmnt}/etc/svc/repository.db
SVCCFG_REPOSITORY=${rdmnt}/etc/svc/repository.db \
    pfexec /usr/sbin/svccfg -v import ${rdmnt}/lib/svc/manifest/system/early-manifest-import.xml
    
#SVCCFG_REPOSITORY=${rdmnt}/etc/svc/repository.db \
#    pfexec /usr/sbin/svccfg -v import ${rdmnt}/lib/svc/manifest
#    /system/early-manifest-import.xml
#SVCCFG_REPOSITORY=${rdmnt}/etc/svc/repository.db pfexec /usr/sbin/svccfg -v import ${rdmnt}/lib/svc/manifest

exit 0
