#!/bin/bash
#
# Install (rsync) this local imgadm to the mounted platform image
# (per `/usbkey/scripts/mount-image.sh -w`) on the given smartos node.
#

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail


#---- support stuff

function fatal {
    echo "$0: fatal error: $*"
    exit 1
}


#---- mainline

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1
if [[ -z "$NODE" ]]; then
    echo "error: no NODE argument given"
    echo ""
    echo "Usage:"
    echo "    ./tools/install-to-mounted-image NODE"
    exit 1
fi
SSH_OPTIONS="-q -i $HOME/.ssh/automation.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
SSH="ssh $SSH_OPTIONS"
SCP="scp $SSH_OPTIONS"


INSTALLIMAGE=$TOP/build/installimage
[[ -d "$INSTALLIMAGE" ]] \
    || fatal "no $INSTALLIMAGE, did you forget to 'make installimage'?"


$SSH -T $NODE <<SCRIPT

function fatal {
    echo "$0: fatal error: $*"
    exit 1
}

[[ -d /image/usr ]] \
    || fatal "no /image/usr, need to '/usbkey/scripts/mount-image.sh -w'"

if [[ -f /image/usr/img/sbin/imgadm-repair ]]; then
    mv /image/usr/img /image/usr/img.bak
fi

SCRIPT

rsync -av $INSTALLIMAGE/ $NODE:/image/usr/img/

echo "Now run this:"
echo "  ssh $NODE '/usbkey/scripts/umount-image.sh && reboot'"
