#!/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

if [[ ! -f /root/.ssh/authorized_keys ]]; then
    authorized_keys=$(/lib/smartdc/mdata-get root_authorized_keys)
    if [[ -n ${authorized_keys} ]]; then
        mkdir -p /root/.ssh
        echo "${authorized_keys}" > /root/.ssh/authorized_keys
        chmod 700 /root/.ssh
        chmod 600 /root/.ssh/authorized_keys
    fi
fi

exit 0
