'\" te
.\"  Copyright (c) 1983 Regents of the University of California. All rights reserved. The Berkeley software License Agreement specifies the terms and conditions for redistribution. Copyright (c) 2004, Sun Microsystems, Inc. All Rights Reserved
.TH auto_ef 1 "26 Sep 2004" "SunOS 5.11" "User Commands"
.SH NAME
auto_ef \- auto encoding finder
.SH SYNOPSIS
.LP
.nf
\fB/usr/bin/auto_ef\fR [\fB-e\fR \fIencoding_list\fR] [\fB-a\fR] [\fB-l\fR \fIlevel\fR] 
     [\fIfile ...\fR]
.fi

.LP
.nf
\fB/usr/bin/auto_ef\fR \fB-h\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fBauto_ef\fR utility identifies the encoding of a given file. The utility judges the encoding by using the \fBiconv\fR code conversion, determining whether a certain code conversion was successful with the file, and also by performing frequency analyses on the character sequences that appear in the file.
.sp
.LP
The \fBauto_ef\fR utility might produce unexpected output if the string is binary, a character table, a localized digit list, or a chronogram, or if the string or file is very small in size (for example, less than one 100 bytes).
.sp
.ne 2
.mk
.na
\fBASCII\fR
.ad
.br
.na
\fBISO-2022-JP\fR
.ad
.RS 20n
.rt  
JIS
.RE

.sp
.ne 2
.mk
.na
\fBeucJP\fR
.ad
.RS 20n
.rt  
Japanese EUC
.RE

.sp
.ne 2
.mk
.na
\fBPCK\fR
.ad
.RS 20n
.rt  
Japanese PC Kanji, CP932, Shift JIS
.RE

.sp
.ne 2
.mk
.na
\fBUTF-8\fR
.ad
.br
.na
\fBko_KR.euc\fR
.ad
.RS 20n
.rt  
Korean EUC
.RE

.sp
.ne 2
.mk
.na
\fBko_KR.cp949\fR
.ad
.RS 20n
.rt  
Unified Hangul
.RE

.sp
.ne 2
.mk
.na
\fBISO-2022-KR\fR
.ad
.RS 20n
.rt  
ISO-2022 Korean
.RE

.sp
.ne 2
.mk
.na
\fBzh_CN.iso2022-CN\fR
.ad
.RS 20n
.rt  
ISO-2022 CN/CN-EXT
.RE

.sp
.ne 2
.mk
.na
\fBzh_CN.euc\fR
.ad
.RS 20n
.rt  
Simplified Chinese EUC, GB2312
.RE

.sp
.ne 2
.mk
.na
\fBGB18030\fR
.ad
.RS 20n
.rt  
Simplified Chinese GB18030/GBK
.RE

.sp
.ne 2
.mk
.na
\fBzh_TW-big5\fR
.ad
.RS 20n
.rt  
BIG5
.RE

.sp
.ne 2
.mk
.na
\fBzh_TW-euc\fR
.ad
.RS 20n
.rt  
Traditional Chinese EUC
.RE

.sp
.ne 2
.mk
.na
\fBzh_TW.hkscs\fR
.ad
.RS 20n
.rt  
Hong Kong BIG5
.RE

.sp
.ne 2
.mk
.na
\fBiso-8859-1\fR
.ad
.RS 20n
.rt  
West European, and similar
.RE

.sp
.ne 2
.mk
.na
\fBiso-8859-2\fR
.ad
.RS 20n
.rt  
East European, and similar
.RE

.sp
.ne 2
.mk
.na
\fBiso-8859-5\fR
.ad
.RS 20n
.rt  
Cyrillic, and similar
.RE

.sp
.ne 2
.mk
.na
\fBiso-8859-6\fR
.ad
.RS 20n
.rt  
Arabic
.RE

.sp
.ne 2
.mk
.na
\fBiso-8859-7\fR
.ad
.RS 20n
.rt  
Greek
.RE

.sp
.ne 2
.mk
.na
\fBiso-8859-8\fR
.ad
.RS 20n
.rt  
Hebrew
.RE

.sp
.ne 2
.mk
.na
\fBCP1250\fR
.ad
.RS 20n
.rt  
windows-1250, corresponding to ISO-8859-2
.RE

.sp
.ne 2
.mk
.na
\fBCP1251\fR
.ad
.RS 20n
.rt  
windows-1251, corresponding to ISO-8859-5
.RE

.sp
.ne 2
.mk
.na
\fBCP1252\fR
.ad
.RS 20n
.rt  
windows-1252, corresponding to ISO-8859-1
.RE

.sp
.ne 2
.mk
.na
\fBCP1253\fR
.ad
.RS 20n
.rt  
windows-1253, corresponding to ISO-8859-7
.RE

.sp
.ne 2
.mk
.na
\fBCP1255\fR
.ad
.RS 20n
.rt  
windows-1255, corresponding to ISO-8859-8
.RE

.sp
.ne 2
.mk
.na
\fBkoi8-r\fR
.ad
.RS 20n
.rt  
corresponding to iso-8859-5
.RE

.sp
.LP
By default, \fBauto_ef\fR returns a single, most likely encoding for text in a specified file. To get all possible encodings for the file, use the \fB-a\fR option.
.sp
.LP
Also by default, \fBauto_ef\fR uses the fastest process to examine the file. For more accurate results, use the \fB-l\fR option.
.sp
.LP
To examine data with a limited set of encodings, use the \fB-e\fR option.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
\fB\fB-a\fR\fR
.ad
.RS 20n
.rt  
Shows all possible encodings in order of possibility, with scores in the range between \fB0.0\fR and \fB1.0\fR. A higher score means a higher possibility. For example,
.sp
.in +2
.nf
example% \fBauto_ef -a test_file\fR
eucJP           0.89
zh_CN.euc       0.04
ko_KR.euc       0.01
.fi
.in -2
.sp

Without this option, only one encoding with the highest score is shown.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-e\fR \fIencoding_list\fR\fR
.ad
.RS 20n
.rt  
Examines data only with specified encodings. For example, when \fIencoding_list\fR is specified as "\fBko_KR.euc:ko_KR.cp949\fR", \fBauto_ef\fR examines text only with \fBCP949\fR and \fBko_KR.euc\fR. Without this option, \fBauto_ef\fR examines text with all encodings. Multiple encodings can be specified by separating the encodings using a colon (\fB:\fR).
.RE

.sp
.ne 2
.mk
.na
\fB\fB-h\fR\fR
.ad
.RS 20n
.rt  
Shows the usage message.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-l\fR \fIlevel\fR\fR
.ad
.RS 20n
.rt  
Specifies the level of judgment. The value of \fIlevel\fR can be \fB0\fR, \fB1\fR, \fB2\fR, or \fB3\fR. Level \fB3\fR produces the best result but can be slow. Level \fB0\fR is fastest but results can be less accurate than in higher levels. The default is level \fB0\fR.
.RE

.SH OPERANDS
.sp
.LP
The following operands are supported:
.sp
.ne 2
.mk
.na
\fB\fIfile\fR\fR
.ad
.RS 8n
.rt  
File name to examine.
.RE

.SH EXAMPLES
.LP
\fBExample 1 \fRExamining encoding of a file
.sp
.in +2
.nf
example% \fBauto_ef \fIfile_name\fR\fR
.fi
.in -2
.sp

.LP
\fBExample 2 \fRExamining encoding of a file at level 2.
.sp
.in +2
.nf
example% \fBauto_ef -l 2 \fIfile_name\fR\fR
.fi
.in -2
.sp

.LP
\fBExample 3 \fRExamining encoding of a file with only eucJP or ko_KR.euc
.sp
.in +2
.nf
example% \fBauto_ef -e "eucJP:ko_KR.euc" \fIfile_name\fR\fR
.fi
.in -2
.sp

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
Successful completion
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
An error occurred.
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWautoef
_
Interface StabilitySee below.
.TE

.sp
.LP
Interface Stability of output format, when option \fB-a\fR is specified, is Evolving. Other interfaces are Stable.
.SH SEE ALSO
.sp
.LP
\fBauto_ef\fR(3EXT), \fBlibauto_ef\fR(3LIB), \fBattributes\fR(5)
.sp
.LP
\fIInternational Language Environments Guide\fR
