'\" te
.\" Copyright (C) 2005, Sun Microsystems, Inc. All Rights Reserved
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH nischgrp 1 "2 Dec 2005" "SunOS 5.11" "User Commands"
.SH NAME
nischgrp \- change the group owner of a NIS+ object
.SH SYNOPSIS
.LP
.nf
\fBnischgrp\fR [\fB-AfLP\fR] \fIgroup\fR \fIname\fR...
.fi

.SH DESCRIPTION
.sp
.LP
\fBnischgrp\fR changes the group owner of the \fBNIS+\fR objects or entries specified by \fIname\fR to the specified \fBNIS+\fR \fIgroup\fR. Entries are specified using indexed names (see \fBnismatch\fR(1)). If \fIgroup\fR is not a fully qualified  \fBNIS+\fR group name, it will be resolved using the directory search path (see \fBnisdefaults\fR(1)).
.sp
.LP
The only restriction on changing an object's group owner is  that you must have modify permissions for the object.
.sp
.LP
This command will fail if the master \fBNIS+\fR server is not running.
.sp
.LP
The  \fBNIS+\fR server will check the validity of the group name prior to effecting the  modification.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
\fB\fB-A\fR\fR
.ad
.RS 6n
.rt  
Modify all entries in all tables in the concatenation path that match the search criterion specified in \fIname\fR. This option implies the \fB-P\fR switch.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-f\fR\fR
.ad
.RS 6n
.rt  
Force the operation and fail silently if it does not succeed.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-L\fR\fR
.ad
.RS 6n
.rt  
Follow links and change the group owner of the linked object or entries rather than the group owner of the link itself.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-P\fR\fR
.ad
.RS 6n
.rt  
Follow the concatenation path within a named table. This option only makes sense when either \fIname\fR is an indexed name or the \fB-L\fR switch is also specified and the named object is a link pointing to entries.
.RE

.SH EXAMPLES
.LP
\fBExample 1 \fRUsing the \fBnischgrp\fR Command
.sp
.LP
The following two examples show how to change the group owner of an object to a group in a different domain, and how to change it to a group in the local domain, respectively.

.sp
.in +2
.nf
example% nischgrp newgroup.remote.domain. object
example% nischgrp my-buds object
.fi
.in -2
.sp

.sp
.LP
This example shows how to change the group owner for a password entry.

.sp
.in +2
.nf
example% nischgrp admins '[uid=99],passwd.org_dir'
.fi
.in -2
.sp

.sp
.LP
In the previous example, \fBadmins\fR is a \fBNIS+\fR group in the same domain.

.sp
.LP
The next two examples change the group owner of the object or entries pointed to by a link, and the group owner of all entries in the \fBhobbies\fR table.

.sp
.in +2
.nf
example% nischgrp -L my-buds linkname
example% nischgrp my-buds '[],hobbies'
.fi
.in -2
.sp

.SH ENVIRONMENT VARIABLES
.sp
.ne 2
.mk
.na
\fB\fBNIS_PATH\fR \fR
.ad
.RS 13n
.rt  
If this variable is set, and the \fBNIS+\fR name is not fully qualified, each directory specified will be searched until the object is found (see \fBnisdefaults\fR(1)).
.RE

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
Successful operation.
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
Operation failed.
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWnisu
.TE

.SH SEE ALSO
.sp
.LP
\fBNIS+\fR(1), \fBnischmod\fR(1), \fBnischown\fR(1), \fBnisdefaults\fR(1), \fBnisgrpadm\fR(1), \fBnismatch\fR(1), \fBnis_objects\fR(3NSL), \fBattributes\fR(5)
.SH NOTES
.sp
.LP
NIS+ might not be supported in future releases of the Solaris operating system. Tools to aid the migration from NIS+ to LDAP are available in the current Solaris release. For more information, visit http://www.sun.com/directory/nisplus/transition.html.
