'\" te
.\" Copyright (C) 2005, Sun Microsystems, Inc. All Rights Reserved
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH nistest 1 "2 Dec 2005" "SunOS 5.11" "User Commands"
.SH NAME
nistest \- return the state of the NIS+ namespace using a conditional expression
.SH SYNOPSIS
.LP
.nf
\fBnistest\fR [\fB-ALMP\fR] [\fB-a\fR \fIrights\fR | \fB-t\fR \fItype\fR] \fIobject\fR
.fi

.LP
.nf
\fBnistest\fR [\fB-ALMP\fR] [\fB-a\fR \fIrights\fR] \fIindexedname\fR
.fi

.LP
.nf
\fBnistest\fR \fB-c\fR \fIdir1\fR \fIop\fR \fIdir2\fR
.fi

.SH DESCRIPTION
.sp
.LP
\fBnistest\fR provides a way for shell scripts and other programs to test for the existence, type, and access rights of objects and entries.  Entries are named using indexed names. See \fBnismatch\fR(1). With the \fB-c\fR option, directory names can be compared to test where they lie in relation to each other in the namespace.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
\fB\fB-a\fR\fI rights\fR\fR
.ad
.RS 13n
.rt  
This option is used to verify that the current process has the  desired or required access rights on the named object or entries. The access rights are specified in the same way as the \fBnischmod\fR(1) command.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-A\fR\fR
.ad
.RS 13n
.rt  
All data. This option specifies that the data within the table and all of  the data in tables in the initial table's concatenation path be returned. This option is only valid when using indexed names or following links.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-L\fR\fR
.ad
.RS 13n
.rt  
Follow links.  If the object named by \fIobject\fR or the tablename component of \fIindexedname\fR names a  \fBLINK\fR type object,  the link is followed when this switch is present.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-M\fR\fR
.ad
.RS 13n
.rt  
Master server only. This option specifies that the lookup should be sent to the master server of the named data. This guarantees that the most up to date information is seen at the possible expense that the master server may be busy.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-P\fR\fR
.ad
.RS 13n
.rt  
Follow concatenation path. This option specifies that the lookup should  follow the concatenation path of a table if the initial search is unsuccessful. This option is only valid when using indexed names or following links.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR\fI type\fR\fR
.ad
.RS 13n
.rt  
This option tests the type of \fIobject\fR. The value of \fBtype\fR can be one of the following:  
.sp
.ne 2
.mk
.na
\fB\fBD\fR\fR
.ad
.RS 5n
.rt  
Return true if the object is a directory object.
.RE

.sp
.ne 2
.mk
.na
\fB\fBG\fR\fR
.ad
.RS 5n
.rt  
Return true if the object is a group object.
.RE

.sp
.ne 2
.mk
.na
\fB\fBL\fR\fR
.ad
.RS 5n
.rt  
Return true if the object is a link object.
.RE

.sp
.ne 2
.mk
.na
\fB\fBP\fR\fR
.ad
.RS 5n
.rt  
Return true if the object is a private object.
.RE

.sp
.ne 2
.mk
.na
\fB\fBT\fR\fR
.ad
.RS 5n
.rt  
Return true if the object is a table object.
.RE

.RE

.sp
.ne 2
.mk
.na
\fB\fB-c\fR\fR
.ad
.RS 13n
.rt  
Test whether or not two directory names have a certain relationship to each other, for example, higher than (ht) or lower than (lt).  The complete list of values for \fIop\fR can be displayed by using the \fB-c\fR \fBoption\fR with no arguments.
.RE

.SH EXAMPLES
.LP
\fBExample 1 \fRUsing the \fBnistest\fR Command
.sp
.LP
When testing for access rights,  \fBnistest\fR returns success (0) if the specified rights are granted to the current user. Thus, testing for access rights:

.sp
.in +2
.nf
example% \fBnistest -a w=mr skippy.domain\fR
.fi
.in -2
.sp

.sp
.LP
Tests that all authenticated NIS+ clients have read and modify access to the object named \fIskippy.domain\fR.

.sp
.LP
Testing for access on a particular entry in a table can be accomplished using the indexed name syntax. The following example tests to see if an entry in the password table can be modified:

.sp
.in +2
.nf
example% \fBnistest -a o=m '[uid=99],passwd.org_dir'\fR
.fi
.in -2
.sp

.sp
.LP
To test if a directory lies higher in the namespace than another directory, use the \fB-c\fR option with an \fIop\fR of \fBht\fR (higher than) as in the following example (which would return true):

.sp
.in +2
.nf
example% \fBnistest -c dom.com. ht lower.dom.com.\fR
.fi
.in -2
.sp

.SH ENVIRONMENT VARIABLES
.sp
.ne 2
.mk
.na
\fB\fBNIS_PATH\fR \fR
.ad
.RS 13n
.rt  
If this variable is set, and the NIS+ name is not fully qualified, each directory specified will be searched until the object is found. See \fBnisdefaults\fR(1).
.RE

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
Successful operation.
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
Failure due to object not present, not of specified type, and/or no such access.
.RE

.sp
.ne 2
.mk
.na
\fB\fB2\fR\fR
.ad
.RS 5n
.rt  
Failure due to illegal usage.
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWnisu
.TE

.SH SEE ALSO
.sp
.LP
\fBNIS+\fR(1), \fBnischmod\fR(1), \fBnisdefaults\fR(1), \fBnismatch\fR(1), \fBattributes\fR(5)
.SH NOTES
.sp
.LP
NIS+ might not be supported in future releases of the Solaris operating system. Tools to aid the migration from NIS+ to LDAP are available in the current Solaris release. For more information, visit http://www.sun.com/directory/nisplus/transition.html.
