'\" te
.\"  Copyright (c) 1999, Sun Microsystems, Inc. All Rights Reserved
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH sccs-delta 1 "1 Nov 1999" "SunOS 5.11" "User Commands"
.SH NAME
sccs-delta, delta \- make a delta to an SCCS file
.SH SYNOPSIS
.LP
.nf
\fB/usr/ccs/bin/delta\fR [\fB-dnps\fR] [\fB-g\fR \fIsid-list\fR | \fB-g\fR\fIsid-list\fR] 
     [\fB-m\fR \fImr-list\fR | \fB-m\fR\fImr-list\fR] [\fB-r\fR \fIsid\fR | \fB-r\fR\fIsid\fR] 
     [\fB-y\fR [\fIcomment\fR]] \fI s.filename\fR...
.fi

.LP
.nf
\fB/usr/xpg4/bin/delta\fR [\fB-dnps\fR] [\fB-g\fR \fIsid-list\fR | \fB-g\fR\fIsid-list\fR] 
     [\fB-m\fR \fImr-list\fR | \fB-m\fR\fImr-list\fR] [\fB-r\fR \fIsid\fR | \fB-r\fR\fIsid\fR] 
     [\fB-y\fR [\fIcomment\fR]] \fI s.filename\fR...
.fi

.SH DESCRIPTION
.sp
.LP
The \fBdelta\fR utility checks in a record of the line-by-line differences made to a checked-out version of a file under \fBSCCS\fR control. These changes are taken from the writable working copy that was retrieved using the \fBSCCS\fR \fBget\fR command (see \fBsccs-get\fR(1)). This working copy does not have the `\fBs.\fR' prefix, and is also referred to as a \fBg\fR-file.
.sp
.LP
If a directory name is used in place of the \fIs.filename\fR argument, the \fBdelta\fR command applies to all \fBs.\fRfiles in that directory. Unreadable \fBs.\fRfiles produce an error; processing continues with the next file (if any). The use of `\fB\(mi\fR\&' as the \fIs.filename\fR argument indicates that the names of files are to be read from the standard input, one \fBs.\fRfile per line (requires \fB-y\fR, and in some cases, \fB-m\fR).
.sp
.LP
\fBdelta\fR may issue prompts on the standard output depending upon the options specified and the flags that are set in the \fBs.\fRfile (see \fBsccs-admin\fR(1), and the \fB-m\fR and \fB-y\fR options below, for details).
.SS "/usr/xpg4/bin/delta"
.sp
.LP
The \fBSID\fR of the delta is not echoed to \fBstdout\fR.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fR
.ad
.RS 28n
.rt  
Use command \fBdiff\fR(1) instead of \fBbdiff\fR(1). Returns exit status \fB2\fR if \fIs.filename\fR argument is not specified.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-n\fR\fR
.ad
.RS 28n
.rt  
Retain the edited \fBg\fR-file, which is normally removed at the completion of processing.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-p\fR\fR
.ad
.RS 28n
.rt  
Display line-by-line differences (in \fBdiff\fR(1) format) on the standard output.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR\fR
.ad
.RS 28n
.rt  
Silent.  Do not display warning or confirmation messages.  Do not suppress error messages (which are written to standard error).
.RE

.sp
.ne 2
.mk
.na
\fB\fB-g\fR \fIsid-list\fR | \fB-g\fR\fIsid-list\fR\fR
.ad
.RS 28n
.rt  
Specify a list of deltas to omit when the file is accessed at the \fBSCCS\fR version \fBID\fR (\fBSID\fR) created by this delta. \fIsid-list\fR is a comma-separated list of \fBSID\fRs. To specify a range of deltas, use a `\fB\(mi\fR\&' separator instead of a comma, between two \fBSID\fRs in the list.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-m\fR \fImr-list\fR | \fB-m\fR\fImr-list\fR\fR
.ad
.RS 28n
.rt  
If the SCCS file has the \fBv\fR flag set (see \fBsccs-admin\fR(1)), you must supply one or more Modification Request (MR) numbers for the new delta. When specifying more than one MR number on the command line, \fImr-list\fR takes the form of a quoted, space-separated list. If \fB-m\fR is not used and the standard input is a terminal, \fBdelta\fR prompts with \fBMRs?\fR for the list (before issuing the \fBcomments?\fR prompt). If the \fBv\fR flag in the \fBs.\fRfile has a value, it is taken to be the name of a program to validate the MR numbers. If that validation program returns a non-zero exit status, \fBdelta\fR terminates without checking in the changes.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-r\fR \fIsid\fR | \fB-r\fR\fIsid\fR\fR
.ad
.RS 28n
.rt  
When two or more versions are checked out, specify the version to check in. This \fBSID\fR value can be either the \fBSID\fR specified on the \fBget\fR command line, or the \fBSID\fR of the new version to be checked in as reported by \fBget\fR. A diagnostic results if the specified \fBSID\fR is ambiguous, or if one is required but not supplied.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-y\fR[\fIcomment\fR]\fR
.ad
.RS 28n
.rt  
Supply a comment for the delta table (version log). A null comment is accepted, and produces an empty commentary in the log. If \fB-y\fR is not specified and the standard input is a terminal, \fBdelta\fR prompts with `\fBcomments?\fR'. An unescaped NEWLINE terminates the comment.
.RE

.SH ENVIRONMENT VARIABLES
.sp
.LP
See \fBenviron\fR(5) for descriptions of the following environment variables that affect the execution of \fBdelta\fR: \fBLANG\fR, \fBLC_ALL\fR, \fBLC_COLLATE\fR, \fBLC_CTYPE\fR, \fBLC_MESSAGES\fR, and \fBNLSPATH\fR.
.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
Successful completion.
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
An error occurred and the \fB-d\fR option had not been specified.
.RE

.sp
.ne 2
.mk
.na
\fB\fB2\fR\fR
.ad
.RS 5n
.rt  
An error occurred, the \fB-d\fR option had been specified, and the \fIs.filename\fR argument was not specified.
.RE

.SH FILES
.sp
.ne 2
.mk
.na
\fB\fBd.file\fR\fR
.ad
.RS 10n
.rt  
temporary file of differences
.RE

.sp
.ne 2
.mk
.na
\fB\fBp.file\fR\fR
.ad
.RS 10n
.rt  
lock file for a checked-out version
.RE

.sp
.ne 2
.mk
.na
\fB\fBq.file\fR\fR
.ad
.RS 10n
.rt  
temporary file
.RE

.sp
.ne 2
.mk
.na
\fB\fBs.file\fR\fR
.ad
.RS 10n
.rt  
\fBSCCS\fR history file
.RE

.sp
.ne 2
.mk
.na
\fB\fBx.file\fR\fR
.ad
.RS 10n
.rt  
temporary copy of the \fBs.\fRfile
.RE

.sp
.ne 2
.mk
.na
\fB\fBz.file\fR\fR
.ad
.RS 10n
.rt  
temporary file
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.SS "/usr/ccs/bin/delta"
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
.TE

.SS "/usr/xpg4/bin/delta"
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWxcu4t
_
Interface StabilityStandard
.TE

.SH SEE ALSO
.sp
.LP
\fBbdiff\fR(1), \fBdiff\fR(1), \fBsccs-admin\fR(1), \fBsccs-cdc\fR(1), \fBsccs-get\fR(1), \fBsccs-help\fR(1), \fBsccs-prs\fR(1), \fBsccs-prt\fR(1), \fBsccs-rmdel\fR(1), \fBsccs-sccsdiff\fR(1), \fBsccs-unget\fR(1), \fBsccs\fR(1), \fBwhat\fR(1), \fBsccsfile\fR(4), \fBattributes\fR(5), \fBenviron\fR(5), \fBstandards\fR(5)
.SH DIAGNOSTICS
.sp
.LP
Use the \fBSCCS\fR \fBhelp\fR command for explanations (see \fBsccs-help\fR(1)).
.SH WARNINGS
.sp
.LP
Lines beginning with an \fBASCII SOH\fR character (binary 001) cannot be placed in the \fBSCCS\fR file unless the \fBSOH\fR is escaped. This character has special meaning to \fBSCCS\fR (see \fBsccsfile\fR(4)) and produces an error.
