'\" te
.\" Copyright (c) 2007, Sun Microsystems, Inc.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH sccs-prt 1 "2 Jul 2007" "SunOS 5.11" "User Commands"
.SH NAME
sccs-prt, prt \- display delta table information from an SCCS file
.SH SYNOPSIS
.LP
.nf
\fBprt\fR [\fB-abdefistu\fR] [\fB-c\fR\fIdate-time\fR] [\fB-r\fR\fIdate-time\fR] 
     [\fB-y\fR\fIsid\fR] \fIs.filename\fR...
.fi

.SH DESCRIPTION
.sp
.LP
\fBprt\fR prints selected portions of an \fBSCCS\fR file.  By default, it prints the delta table (version log).
.sp
.LP
If a directory name is used in place of the \fIs.filename\fR argument, the \fBprt\fR command applies to all \fBs.\fRfiles in that directory. Unreadable \fBs.\fRfiles produce an error; processing continues with the next file (if any). The use of `\fB\(mi\fR\&' as the \fIs.filename\fR argument indicates that the names of files are to be read from the standard input, one \fBs.\fRfile per line.
.SH OPTIONS
.sp
.LP
If any option other than \fB-y\fR, \fB-c\fR, or \fB-r\fR is supplied, the name of each file being processed (preceded by one \fBNEWLINE\fR and followed by two \fBNEWLINE\fR characters) appears above its contents.
.sp
.LP
If none of the \fB-u\fR, \fB-f\fR, \fB-t\fR, or \fB-b\fR options are used, \fB-d\fR is assumed. \fB-s\fR, \fB-i\fR are mutually exclusive, as are \fB-c\fR and \fB-r\fR.
.sp
.ne 2
.mk
.na
\fB\fB-a\fR\fR
.ad
.RS 15n
.rt  
Display log entries for all deltas, including those marked as removed.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-b\fR\fR
.ad
.RS 15n
.rt  
Print the body of the \fBs.\fRfile.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fR
.ad
.RS 15n
.rt  
Print delta table entries.  This is the default.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-e\fR\fR
.ad
.RS 15n
.rt  
Everything.  This option implies \fB-d\fR, \fB-i\fR, \fB-u\fR, \fB-f\fR, and \fB-t\fR.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-f\fR\fR
.ad
.RS 15n
.rt  
Print the flags of each named \fBs.\fRfile.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-i\fR\fR
.ad
.RS 15n
.rt  
Print the serial numbers of included, excluded, and ignored deltas.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR\fR
.ad
.RS 15n
.rt  
Print only the first line of the delta table entries; that is, only up to the statistics.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR\fR
.ad
.RS 15n
.rt  
Print the descriptive text contained in the \fBs.\fRfile.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-u\fR\fR
.ad
.RS 15n
.rt  
Print the user-names and/or numerical group \fBIDs\fR of users allowed to make deltas.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-c\fR\fIdate-time\fR\fR
.ad
.RS 15n
.rt  
Exclude delta table entries that are specified cutoff date and time. Each entry is printed as a single line, preceded by the name of the \fBSCCS\fR file.  This format (also produced by \fB-r\fR \fB,\fR and \fB-y\fR) makes it easy to sort multiple delta tables in chronological order. When both \fB-y\fR and \fB-c\fR, or \fB-y\fR and \fB-r\fR are supplied, \fBprt\fR stops printing when the first of the two conditions is met.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-r\fR\fIdate-time\fR\fR
.ad
.RS 15n
.rt  
Exclude delta table entries that are newer than the specified cutoff date and time.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-y\fR\fIsid\fR\fR
.ad
.RS 15n
.rt  
Exclude delta table entries made prior to the \fBSID\fR specified.  If no delta in the table has the specified SID, the entire table is printed.  If no \fBSID\fR is specified, the most recent delta is printed.
.RE

.SH USAGE
.SS "Output Format"
.sp
.LP
The following format is used to print those portions of the \fBs.\fRfile that are specified by the various options.
.RS +4
.TP
.ie t \(bu
.el o
\fBNEWLINE\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
Type of delta (\fBD\fR or \fBR\fR)
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBSPACE\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBSCCS\fR delta  \fBID\fR (SID)
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBTAB\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
Date and time of creation in the form: \fIyy\fR\fB/\fR\fImm\fR\fB/\fR\fBdd\fR \fIhh\fR\fB/\fR\fImm\fR\fB/\fR\fIss\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBSPACE\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
Username the delta's creator
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBTAB\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
Serial number of the delta
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBSPACE\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
Predecessor delta's serial number
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBTAB\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
Line-by-line change statistics in the form: \fIinserted\fR\fB/\fR\fIdeleted\fR\fB/\fR\fIunchanged\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBNEWLINE\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
List of included deltas, followed by a \fBNEWLINE\fR (only if there were any such deltas and the \fB-i\fR options was used)
.RE
.RS +4
.TP
.ie t \(bu
.el o
List of excluded deltas, followed by a \fBNEWLINE\fR (only if there were any such deltas and the \fB-i\fR options was used)
.RE
.RS +4
.TP
.ie t \(bu
.el o
List of ignored deltas, followed by a \fBNEWLINE\fR (only if there were any such deltas and the \fB-i\fR options was used)
.RE
.RS +4
.TP
.ie t \(bu
.el o
List of modification requests (MRs), followed by a \fBNEWLINE\fR (only if any \fBMR\fR numbers were supplied).
.RE
.RS +4
.TP
.ie t \(bu
.el o
Lines of the delta commentary (if any), followed by a \fBNEWLINE.\fR
.RE
.SH EXAMPLES
.LP
\fBExample 1 \fRProducing a Display of the Delta Table
.sp
.LP
The following command produces a one-line display of the delta table entry for the most recent version:

.sp
.in +2
.nf
example% prt -y program.c
s.program.c:  D 1.6   88/07/06 21:39:39 username   5 4 00159/00080/00636
.fi
.in -2
.sp

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWsprot
.TE

.SH SEE ALSO
.sp
.LP
\fBsccs\fR(1), \fBsccs-cdc\fR(1), \fBsccs-delta\fR(1), \fBsccs-get\fR(1), \fBsccs-help\fR(1), \fBsccs-prs\fR(1), \fBsccs-sact\fR(1), \fBsccs-sccsdiff\fR(1), \fBwhat\fR(1), \fBsccsfile\fR(4), \fBattributes\fR(5)
.SH DIAGNOSTICS
.sp
.LP
Use the \fBSCCS\fR \fBhelp\fR command for explanations (see \fBsccs-help\fR(1)).
