#!/bin/sh
#
# Copyright 2020 Joyent, Inc.
#

for f in *.di
do
    disklayout -f $f > /var/tmp/$f.out
    printf "%-16s " $f.out
    diff -u $f.out /var/tmp/$f.out
    rm -f /var/tmp/$f.out
done

echo
echo "no spares"
for f in *.di
do
    disklayout -f $f -s 0 > /var/tmp/$f.out
    printf "%-16s " $f.out
    diff -u $f.0s.out /var/tmp/$f.out
    rm -f /var/tmp/$f.out
done

echo
echo "1 spare"
for f in *.di
do
    disklayout -f $f -s 1 > /var/tmp/$f.out
    printf "%-16s " $f.out
    diff -u $f.1s.out /var/tmp/$f.out
    rm -f /var/tmp/$f.out
done

echo
echo "standalone tests"

disklayout -f insane.di -c > /var/tmp/insane.out
printf "%-16s " insanec.out
diff -u insane.di.c.out /var/tmp/insane.out
rm -f /var/tmp/insane.out

disklayout -f insane.di -c -s 0 > /var/tmp/insane.out
printf "%-16s " insanec0.out
diff -u insane.di.c0.out /var/tmp/insane.out
rm -f /var/tmp/insane.out

disklayout -f insane.di -c -s 1 > /var/tmp/insane.out
printf "%-16s " insanec1.out
diff -u insane.di.c1.out /var/tmp/insane.out
rm -f /var/tmp/insane.out

disklayout -f s8.di mirror > /var/tmp/s8.out
printf "%-16s " 8mirror.out
diff -u s8.di.m.out /var/tmp/s8.out
rm -f /var/tmp/s8.out

disklayout -f s8.di raidz1 > /var/tmp/s8.out
printf "%-16s " 8z1.out
diff -u s8.di.z1.out /var/tmp/s8.out
rm -f /var/tmp/s8.out

disklayout -f s8.di raidz2 > /var/tmp/s8.out
printf "%-16s " 8z2.out
diff -u s8.di.z2.out /var/tmp/s8.out
rm -f /var/tmp/s8.out

disklayout -f s8.di raidz3 > /var/tmp/s8.out
printf "%-16s " 8z3.out
diff -u s8.di.z3.out /var/tmp/s8.out
rm -f /var/tmp/s8.out

disklayout -f s8.di -s 0 mirror > /var/tmp/s8.out
printf "%-16s " 8mirror0.out
diff -u s8.di.m0.out /var/tmp/s8.out
rm -f /var/tmp/s8.out

disklayout -f s16.di mirror > /var/tmp/s16.out
printf "%-16s " 16mirror.out
diff -u s16.di.m.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

disklayout -f s16.di raidz1 > /var/tmp/s16.out
printf "%-16s " 16z1.out
diff -u s16.di.z1.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

disklayout -f s16.di raidz2 > /var/tmp/s16.out
printf "%-16s " 16z2.out
diff -u s16.di.z2.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

disklayout -f s16.di raidz3 > /var/tmp/s16.out
printf "%-16s " 16z3.out
diff -u s16.di.z3.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

disklayout -f s16.di -s 0 mirror > /var/tmp/s16.out
printf "%-16s " 16mirror0.out
diff -u s16.di.m0.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

disklayout -f s16.di -s 0 raidz1 > /var/tmp/s16.out
printf "%-16s " 16z1-0.out
diff -u s16.di.z1-0.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

disklayout -f s16.di -s 0 raidz2 > /var/tmp/s16.out
printf "%-16s " 16z2-0.out
diff -u s16.di.z2-0.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

disklayout -f s16.di -s 0 raidz3 > /var/tmp/s16.out
printf "%-16s " 16z3-0.out
diff -u s16.di.z3-0.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

# Width tests

disklayout -s 0 -w 12 -f 60.di > /var/tmp/s60.out
printf "%-16s " 60.0s.w12.out
diff -u 60.di.0s.w12.out /var/tmp/s60.out
rm -f /var/tmp/s60.out

# 6x10
disklayout -s 0 -f 60.di raidz3 > /var/tmp/s60.out
printf "%-16s " 60.0s.z3.out
diff -u 60.di.0s.z3.out /var/tmp/s60.out
rm -f /var/tmp/s60.out

# 4x15
disklayout -s 0 -w 15 -f 60.di raidz3 > /var/tmp/s60.out
printf "%-16s " 60.0s.w15.z3.out
diff -u 60.di.0s.w15.z3.out /var/tmp/s60.out
rm -f /var/tmp/s60.out

# should be same as above, but without explicit raidz3
disklayout -s 0 -w 15 -f 60.di > /var/tmp/s60.out
printf "%-16s " 60.0s.w15.out
diff -u 60.di.0s.w15.z3.out /var/tmp/s60.out
rm -f /var/tmp/s60.out

disklayout -s 0 -w 17 -f 36.di > /var/tmp/s34.out
printf "%-16s " 36.0s.w17.z3.out
diff -u 36.0s.w17.z3.out /var/tmp/s34.out
rm -f /var/tmp/s34.out

disklayout -w 15 -f s16.di > /var/tmp/s16.out
printf "%-16s " 16.w15.out
diff -u s16.di.w15.out /var/tmp/s16.out
rm -f /var/tmp/s16.out

# raidz2 (9-wide overlaps with valid raidz3 range width)
disklayout -w 9 -f s18.di > /var/tmp/s18.out
printf "%-16s " 18.w9.out
diff -u s18.di.w9.out /var/tmp/s18.out
rm -f /var/tmp/s18.out

disklayout -w 9 -f s18.di raidz3 > /var/tmp/s18.out
printf "%-16s " 18.w9.out
diff -u s18.di.w9.z3.out /var/tmp/s18.out
rm -f /var/tmp/s18.out

# 3-way mirror
disklayout -w 3 -f 3.di mirror > /var/tmp/3.out
printf "%-16s " 3.w3.m.out
diff -u 3.di.w3.m.out /var/tmp/3.out
rm -f /var/tmp/3.out

# Next two tests specify width larger than default max
disklayout -w 7 -f 7.di raidz1 > /var/tmp/7.out
printf "%-16s " 7.w7.z1.out
diff -u 7.di.w7.z1.out /var/tmp/7.out
rm -f /var/tmp/7.out

disklayout -w 21 -f 60.di raidz3 > /var/tmp/21.out
printf "%-16s " 60.di.w21.z3.out
diff -u 60.di.w21.z3.out /var/tmp/21.out
rm -f /var/tmp/21.out

# 36 disk server with raidz1 - defaults to 3-wide stripes
disklayout -f 36h.di -s 0 raidz1 > /var/tmp/3.out
printf "%-16s " 36.w3.z1.out
diff -u 36.di.w3.z1.out /var/tmp/3.out
rm -f /var/tmp/3.out

# 36 disk server with 12-wide raidz1 for max capacity
disklayout -f 36h.di -w 12 -s 0 raidz1 > /var/tmp/12.out
printf "%-16s " 36.w12.z1.out
diff -u 36.di.w12.z1.out /var/tmp/12.out
rm -f /var/tmp/12.out

echo
echo "excluded disks tests"

disklayout -f opt-e.in -e "foo,bar" mirror >/var/tmp/opt-e.out
printf "%-16s " "opt-e.none.out"
diff -u opt-e.none.out /var/tmp/opt-e.out
rm -f /var/tmp/opt-e.out

disklayout -f opt-e.in -e "disk6" mirror >/var/tmp/opt-e.out
printf "%-16s " "opt-e.disk6.out"
diff -u opt-e.disk6.out /var/tmp/opt-e.out
rm -f /var/tmp/opt-e.out

disklayout -f opt-e.in -e "disk1" mirror >/var/tmp/opt-e.out
printf "%-16s " "opt-e.disk1.out"
diff -u opt-e.disk1.out /var/tmp/opt-e.out
rm -f /var/tmp/opt-e.out

disklayout -f opt-e.in -e "disk1,disk2" mirror >/var/tmp/opt-e.out
printf "%-16s " "opt-e.disk1,2.out"
diff -u opt-e.disk1,2.out /var/tmp/opt-e.out
rm -f /var/tmp/opt-e.out

disklayout -f opt-e.in -e "disk2,disk3,disk4" mirror >/var/tmp/opt-e.out
printf "%-16s " "opt-e.disk2,3,4.out"
diff -u opt-e.disk2,3,4.out /var/tmp/opt-e.out
rm -f /var/tmp/opt-e.out

echo
echo "invalid input tests"

disklayout -s 5 -f 7.di raidz1 > /var/tmp/err.out
printf "%-16s " 7.5s.z1.out
diff -u 7.di.5s.z1.out /var/tmp/err.out
rm -f /var/tmp/err.out

disklayout -s 2 -w 6 -f 7.di raidz1 > /var/tmp/err.out
printf "%-16s " 7.2s.w6.z1.out
diff -u 7.di.2s.w6.z1.out /var/tmp/err.out
rm -f /var/tmp/err.out

disklayout -w 6 -f 7.di raidz2 > /var/tmp/err.out
printf "%-16s " 7.w6.z2.out
diff -u 7.di.w6.z2.out /var/tmp/err.out
rm -f /var/tmp/err.out

disklayout -w 15 -s 2 -f s16.di raidz3 > /var/tmp/err.out
printf "%-16s " 16.2s.w15.z3.out
diff -u 16.di.2s.w15.z3.out /var/tmp/err.out
rm -f /var/tmp/err.out

disklayout -w 3 -s 3 -f 5.di mirror > /var/tmp/err.out
printf "%-16s " 5.3s.w3.m.out
diff -u 5.di.3s.w3.m.out /var/tmp/err.out
rm -f /var/tmp/err.out

disklayout -s 2 -f 3.di mirror > /var/tmp/err.out
printf "%-16s " 3.2s.m.out
diff -u 3.di.2s.m.out /var/tmp/err.out
rm -f /var/tmp/err.out
