#!/bin/bash
#
# Copyright (c) 2012, Joyent, Inc. All rights reserved.
#
# Run the imgadm tests. This is expected to be run from a SmartOS GZ.
#
# This creates .tap files in the OUTPUT_DIR (/var/tmp/imgadmtest) that
# can be processed by a TAP reader. Testing config and log files are
# also placed in this dir.
#
# Run `./runtests -h` for usage info.
#

if [ "$TRACE" != "" ]; then
    export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail



#---- support functions

function fatal
{
    echo "$(basename $0): fatal error: $*"
    exit 1
}

function cleanup () {
    local status=$?
    if [[ $status -ne 0 ]]; then
        echo "error $status (run 'TRACE=1 $0' for more info)"
    fi
}

function usage
{
    echo "Usage:"
    echo "  runtests [OPTIONS...]"
    echo ""
    echo "Options:"
    echo "  -h           Print this help and exit."
    echo "  -f FILTER    Filter pattern (substring match) for test files to run."
    echo "  -r REPORTER  Use an alternate nodeunit reporter. Default 'tap'."
}



#---- mainline

trap 'cleanup' EXIT

start_time=$(date +%s)

TOP=$(cd $(dirname $0)/../; pwd)
NODEUNIT="/usr/node/bin/node $TOP/node_modules/.bin/nodeunit"


# Options.
opt_test_pattern=
opt_reporter=default
while getopts "hf:" opt
do
    case "$opt" in
        h)
            usage
            exit 0
            ;;
        f)
            opt_test_pattern=$OPTARG
            ;;
        r)
            opt_reporter=$OPTARG
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done


# Guard from running in production.
if [[ -z "$opt_local" ]]; then
if [[ ! -f "/lib/sdc/.sdc-test-no-production-data" ]]; then
    cat <<EOF
To run this test you must create the file:

    /lib/sdc/.sdc-test-no-production-data

after ensuring you have no production data on this SDC.
EOF
    exit 2
fi
fi


# Setup a clean output dir.
OUTPUT_DIR=/var/tmp/imgadmtest
echo "# Setup a clean output dir ($OUTPUT_DIR)."
rm -rf $OUTPUT_DIR
mkdir -p $OUTPUT_DIR


# Simplify: just run everything from $TOP.
cd $TOP


# Run the tests.
echo ""
retval=0
test_files=$(ls -1 test/*.test.js)
if [[ -n "$opt_test_pattern" ]]; then
    test_files=$(echo "$test_files" | grep "$opt_test_pattern" || true)
    echo "# Running filtered set of test files: $test_files"
fi
if [[ -n "$test_files" ]]; then
    if [[ $opt_reporter == "tap" ]]; then
        $NODEUNIT --reporter $opt_reporter $test_files \
            | tee $OUTPUT_DIR/imgadm.tap
    else
        $NODEUNIT --reporter $opt_reporter $test_files
        retval=$?
    fi
fi


if [[ $opt_reporter == "tap" ]]; then
    echo ""
    echo "# test output:"
    ls $OUTPUT_DIR/*.tap

    # Colored summary of results (borrowed from smartos-live.git/src/vm/run-tests).
    echo ""
    echo "# test results:"

    end_time=$(date +%s)
    elapsed=$((${end_time} - ${start_time}))

    tests=$(grep "^# tests [0-9]" $OUTPUT_DIR/*.tap | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
    passed=$(grep "^# pass  [0-9]" $OUTPUT_DIR/*.tap | tr -s ' ' | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
    [[ -z ${tests} ]] && tests=0
    [[ -z ${passed} ]] && passed=0
    fail=$((${tests} - ${passed}))

    echo "# Completed in ${elapsed} seconds."
    echo -e "# \033[32mPASS: ${passed} / ${tests}\033[39m"
    if [[ ${fail} -gt 0 ]]; then
        echo -e "# \033[31mFAIL: ${fail} / ${tests}\033[39m"
    fi
    echo ""

    if [[ ${tests} != ${passed} ]]; then
        exit 1
    fi
else
    exit $retval
fi
