'\" te
.\" Copyright (c) 2005, Sun Microsystems, Inc. All Rights Reserved.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH registration_profile 4 "27 Feb 2006" "SunOS 5.11" "File Formats"
.SH NAME
registration_profile \- template for Basic Registration information
.SH SYNOPSIS
.LP
.nf
\fBregistration.profile\fR
.fi

.SH DESCRIPTION
.sp
.LP
The registration profile is a template for the information provided for Basic Registration. The information in this template is consumed by the \fBsconadm\fR(1M) utility. \fBsconadm\fR is the command-line alternative to the Basic Registration GUI.
.sp
.LP
An example of the registration profile template is provided in \fB/usr/lib/breg/data/RegistrationProfile.properties\fR. This file is owned by root, with read-only permissions. As root, you can copy the file to a location of your choosing and edit the file.
.sp
.LP
The registration profile template contains the following properties:
.sp
.in +2
.nf
userName=
password=
hostName=
subscriptionKey=
portalEnabled=
proxyHostName=
proxyPort=
proxyUserName=
proxyPassword=
.fi
.in -2

.sp
.LP
Values are not required for every property. The filling in or leaving blank a property depends on the task you intend to perform. Possible tasks are registering a new system, reregistering a system, and establishing a proxy. See \fBsconadm\fR(1M) for examples.
.sp
.LP
The properties defined for a registration template are as follows:
.sp
.ne 2
.mk
.na
\fB\fBuserName\fR\fR
.ad
.RS 19n
.rt  
Corresponds to Sun Online Account user name.
.RE

.sp
.ne 2
.mk
.na
\fB\fBpassword\fR\fR
.ad
.RS 19n
.rt  
Corresponds to Sun Online Account password.
.RE

.sp
.ne 2
.mk
.na
\fB\fBhostName\fR\fR
.ad
.RS 19n
.rt  
Hostname of the machine to be registered (defaults to Unix host name, if not provided).
.RE

.sp
.ne 2
.mk
.na
\fB\fBsubscriptionKey\fR\fR
.ad
.RS 19n
.rt  
Enable access to all updates by providing your Sun Subscription Key for entitlement.
.LP
Note - 
.sp
.RS 2
The Sun Subscription Key is now known as the Sun Service Plan Number. However, the name of this field (\fBsubscriptionKey\fR) remains unchanged.
.RE
.RE

.sp
.ne 2
.mk
.na
\fB\fBportalEnabled\fR\fR
.ad
.RS 19n
.rt  
If \fBtrue\fR, enable local client to be managed at the Sun-hosted Update Connection Service. If \fBfalse\fR, disable local client to be managed at the Sun-hosted Update Connection Service.
.RE

.sp
.ne 2
.mk
.na
\fB\fBproxyHostName\fR\fR
.ad
.RS 19n
.rt  
Your HTTP web proxy host name.
.RE

.sp
.ne 2
.mk
.na
\fB\fBproxyPort\fR\fR
.ad
.RS 19n
.rt  
Your HTTP web proxy port number.
.RE

.sp
.ne 2
.mk
.na
\fB\fBproxyUserName\fR\fR
.ad
.RS 19n
.rt  
Your HTTP web proxy user name.
.RE

.sp
.ne 2
.mk
.na
\fB\fBproxyPassword\fR\fR
.ad
.RS 19n
.rt  
Your HTTP web proxy password.
.RE

.SH EXAMPLES
.LP
\fBExample 1 \fRSample Registration Profile
.sp
.LP
Below are the contents of a sample registration profile. Such a profile might be used to specify a proxy server with authentication.

.sp
.in +2
.nf
userName=
password=
hostName=
subscriptionKey=
portalEnabled=
proxyHostName=webcache.mycompany.com
proxyPort=8080
proxyUserName=\fImyCompanyProxyUserName\fR
proxyPassword=\fImyCompanyProxyPassword\fR
.fi
.in -2

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWbrg
_
Interface StabilityStable
.TE

.SH SEE ALSO
.sp
.LP
\fBsconadm\fR(1M), \fBattributes\fR(5)
