'\" te
.\" Copyright (c) 2002, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright 1989 AT&T
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH sccsfile 4 "30 Sep 2002" "SunOS 5.11" "File Formats"
.SH NAME
sccsfile \- format of an SCCS history file
.SH DESCRIPTION
.sp
.LP
An SCCS file is an \fBASCII\fR file consisting of six logical parts:
.sp
.ne 2
.mk
.na
\fB\fIchecksum\fR\fR
.ad
.RS 15n
.rt  
Character count used for error detection.
.RE

.sp
.ne 2
.mk
.na
\fB\fIdelta\fR \fItable\fR\fR
.ad
.RS 15n
.rt  
Log containing version info and statistics about each delta.
.RE

.sp
.ne 2
.mk
.na
\fB\fIusernames\fR\fR
.ad
.RS 15n
.rt  
Login names and/or group IDs of users who may add deltas.
.RE

.sp
.ne 2
.mk
.na
\fB\fIflags\fR\fR
.ad
.RS 15n
.rt  
Definitions of internal keywords.
.RE

.sp
.ne 2
.mk
.na
\fB\fIcomments\fR\fR
.ad
.RS 15n
.rt  
Arbitrary descriptive information about the file.
.RE

.sp
.ne 2
.mk
.na
\fB\fIbody\fR\fR
.ad
.RS 15n
.rt  
the Actual text lines intermixed with control lines.
.RE

.sp
.LP
Each section is described in detail below.
.SS "Conventions"
.sp
.LP
Throughout an SCCS file there are lines which begin with the \fBASCII\fR \fBSOH\fR (start of heading) character (octal 001). This character is hereafter referred to as the \fIcontrol character\fR, and will be represented as `\fB^A\fR'. If a line described below is not depicted as beginning with the control character, it cannot do so and still be within SCCS file format.
.sp
.LP
Entries of the form \fIddddd\fR represent a five digit string (a number between 00000 and 99999).
.SS "Checksum"
.sp
.LP
The checksum is the first line of an SCCS file. The form of the line is:
.sp
.in +2
.nf
^A h\fIddddd\fR
.fi
.in -2

.sp
.LP
The value of the checksum is the sum of all characters, except those contained in the first line. The \fB^Ah\fR provides a \fImagic number\fR of (octal) 064001.
.SS "Delta Table"
.sp
.LP
The delta table consists of a variable number of entries of the form:
.sp
.in +2
.nf
^As \fIinserted\|\fR/\fIdeleted\fR/\fIunchanged\fR
^Ad \fItype  sid  yr\fR/\fImo\fR/\fIda hr\fR:\fImi\fR:\fIse  username  serial-number \e
 predecessor-sn\fR
^Ai \fIinclude-list\fR
^Ax \fIexclude-list\fR
^Ag \fIignored-list\fR
^Am \fImr-number\fR
\&...
^Ac \fIcomments\fR ...
\&...
^Ae 
.fi
.in -2
.sp

.sp
.LP
The first line (\fB^As\fR) contains the number of lines inserted/deleted/unchanged respectively. The second line (\fB^Ad\fR) contains the type of the delta (normal: \fBD\fR and removed: \fBR\fR), the SCCS ID of the delta, the date and time of creation of the delta, the user-name corresponding to the real user ID at the time the delta was created, and the serial numbers of the delta and its predecessor, respectively. The \fB^Ai\fR, \fB^Ax\fR, and \fB^Ag\fR lines contain the serial numbers of deltas included, excluded, and ignored, respectively. These lines do not always appear.
.sp
.LP
The \fB^Am\fR lines (optional) each contain one MR number associated with the delta. The \fB^Ac\fR lines contain comments associated with the delta.
.sp
.LP
The \fB^Ae\fR line ends the delta table entry.
.SS "User Names"
.sp
.LP
The list of user-names and/or numerical group IDs of users who may add deltas to the file, separated by NEWLINE characters. The lines containing these login names and/or numerical group IDs are surrounded by the bracketing lines \fB^Au\fR and \fB^AU\fR. An empty list allows anyone to make a delta.
.SS "Flags"
.sp
.LP
Flags are keywords that are used internally (see \fBsccs-admin\fR(1) for more information on their use).  Each flag line takes the form:
.sp
.in +2
.nf
 ^Af \fIflag\fR
          \fIoptional text\fR
.fi
.in -2

.sp
.LP
The following flags are defined in order of appearance:
.sp
.ne 2
.mk
.na
\fB\fB^Af t\fR \fItype-of-program\fR\fR
.ad
.RS 25n
.rt  
Defines the replacement for the \fB12:24:17\fR ID keyword.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af v\fR \fIprogram-name\fR\fR
.ad
.RS 25n
.rt  
Controls prompting for MR numbers in addition to comments. If the optional text is present, it defines an MR number validity checking program.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af i\fR \fR
.ad
.RS 25n
.rt  
Indicates that the `\fBNo id keywords\fR' message is to generate an error that terminates the SCCS command. Otherwise, the message is treated as a warning only.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af b\fR \fR
.ad
.RS 25n
.rt  
Indicates that the \fB-b\fR option may be used with the SCCS \fBget\fR command to create a branch in the delta tree.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af m\fR \fImodule-name\fR\fR
.ad
.RS 25n
.rt  
Defines the first choice for the replacement text of the \fBsccsfile.4\fR ID keyword.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af f\fR \fIfloor\fR\fR
.ad
.RS 25n
.rt  
Defines the "floor" release, that is, the release below which no deltas may be added.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af c\fR \fIceiling\fR\fR
.ad
.RS 25n
.rt  
Defines the "ceiling" release, that is, the release above which no deltas may be added.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af d\fR \fIdefault-sid\fR\fR
.ad
.RS 25n
.rt  
The \fBd\fR flag defines the default SID to be used when none is specified on an SCCS \fBget\fR command.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af n\fR \fR
.ad
.RS 25n
.rt  
The \fBn\fR flag enables the SCCS \fBdelta\fR command to insert a "null" delta (a delta that applies \fBno\fR changes) in those releases that are skipped when a delta is made in a \fBnew\fR release (for example, when delta 5.1 is made after delta 2.7, releases 3 and 4 are skipped).
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af j\fR \fR
.ad
.RS 25n
.rt  
Enables the SCCS \fBget\fR command to allow concurrent edits of the same base \fBSID\fR.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af l\fR \fIlock-releases\fR\fR
.ad
.RS 25n
.rt  
Defines a list of releases that are locked against editing.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af q\fR \fIuser-defined\fR\fR
.ad
.RS 25n
.rt  
Defines the replacement for the \fB\fR ID keyword.
.RE

.sp
.ne 2
.mk
.na
\fB\fB^Af e\fR \fB0\fR|\fB1\fR\fR
.ad
.RS 25n
.rt  
The \fBe\fR flag indicates whether a source file is encoded or not. A \fB1\fR indicates that the file is encoded. Source files need to be encoded when they contain control characters, or when they do not end with a NEWLINE. The \fBe\fR flag allows files that contain binary data to be checked in.
.RE

.SS "Comments"
.sp
.LP
Arbitrary text surrounded by the bracketing lines \fB^At\fR and \fB^AT\fR. The comments section typically will contain a description of the file's purpose.
.SS "Body"
.sp
.LP
The body consists of text lines and control lines. Text lines do not begin with the control character, control lines do. There are three kinds of control lines: \fIinsert\fR, \fIdelete\fR, and \fIend\fR, represented by:
.sp
.in +2
.nf
^AI \fIddddd\fR
^AD \fIddddd\fR
^AE \fIddddd\fR 
.fi
.in -2
.sp

.sp
.LP
respectively. The digit string is the serial number corresponding to the delta for the control line.
.SH SEE ALSO
.sp
.LP
\fBsccs-admin\fR(1), \fBsccs-cdc\fR(1), \fBsccs-comb\fR(1), \fBsccs-delta\fR(1), \fBsccs-get\fR(1), \fBsccs-help\fR(1), \fBsccs-prs\fR(1), \fBsccs-prt\fR(1), \fBsccs-rmdel\fR(1), \fBsccs-sact\fR(1), \fBsccs-sccsdiff\fR(1), \fBsccs-unget\fR(1), \fBsccs-val\fR(1), \fBsccs\fR(1), \fBwhat\fR(1)
