#!/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

key=$1
if [[ -z ${key} ]]; then
    echo "Usage: $0 <key>"
    exit 1
fi

NC_SOCK=
DISABLE_ECHO="yes"

case $(uname -s) in
    Linux)
        SERIAL_DEV="/dev/ttyS1"
    ;;
    FreeBSD)
        SERIAL_DEV="/dev/cuau1"
    ;;
    SunOS)
        NC_SOCK="/var/run/smartdc/metadata.sock"
        DISABLE_ECHO="no"
    ;;
    *)
        echo "Don't know which serial to use for $(uname -s)"
        exit 1
    ;;
esac

if [[ -n ${NC_SOCK} ]]; then
    coproc nc -U ${NC_SOCK}
    exec <&${COPROC[0]} 3>&${COPROC[1]}
else
    exec <${SERIAL_DEV} 3>>${SERIAL_DEV}
fi

IFS=$'\n'
if [[ ${DISABLE_ECHO} == "yes" ]]; then
    stty -echo
fi

echo "GET ${key}" >&3

# First line will be a status.
read status
if [[ ${status} == "NOTFOUND" ]]; then
    echo "No metadata for ${key}"
    exit 1
elif [[ ${status} != "SUCCESS" ]]; then
    echo "Error getting metadata for key ${key}: ${status}"
    exit 2
fi

export PATH=$PATH:/usr/perl5/bin:/opt/local/bin:/usr/local/bin:/usr/local/perl5/bin
perl -ne 'chomp; if (/^\.$/) { exit 0 }; if (/^\./) { s/^.//; } print "$_\n"'

exit 0
