#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2011 Joyent, Inc.  All rights reserved.
#

unset LD_LIBRARY_PATH
PATH=/usr/bin:/usr/sbin
export PATH

OVER=0
ZONENAME="ALL"

while getopts "oz:" opt
do
	case "$opt" in
	o)	OVER=1;;
	z)	ZONENAME=$OPTARG;;
	*)	printf "zonememstat [-n] [-z zonename]\n"
		exit 1;;
	esac
done
shift OPTIND-1

kstat -c zone_memory_cap | nawk -v zname=$ZONENAME -v over=$OVER 'BEGIN {
	printf("%36s %8s %8s %6s %8s\n", "ZONE", "RSS", "CAP", "NOVER", "POUT");
	}
	{
	if ($1 == "nover") {
		nover = $2
	} else if ($1 == "pagedout") {
		pout = $2 / 1048576
	} else if ($1 == "physcap") {
		cap = $2 / 1048576
	} else if ($1 == "rss") {
		rss = $2 / 1048576
	} else if ($1 == "swap") {
		swap = $2 / 1048576
	} else if ($1 == "swapcap") {
		swapcap = $2 / 1048576
	} else if ($1 == "zonename") {
		if (zname != "ALL" && zname != $2)
			next
		if (over == 1 && nover == 0)
			next
		# If cap is UINT64_MAX / 1048576
		if (cap >= 2147483000)
			printf("%36s %6uMB %8s %6s %8s\n",
			    $2, rss, "-", "-", "-");
		else
			printf("%36s %6uMB %6uMB %6u %6uMB\n",
			    $2, rss, cap, nover, pout);
	}
}'
