#!/usr/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# This script exists to apply SDC specific changes to zones on upgrade from
# SDC6.5 to SDC7. It is run by vmadmd the first time a zone missing the 'v'
# property is booted on SDC7. See also OS-1103.
#
# The only argument that is passed is the UUID of the VM to be upgraded. It
# should exit 0 when the upgrade was successful and non-zero when it failed.
#

set -o xtrace
set -o errexit

UUID=$1
if [[ -z ${UUID} || -n $2 ]]; then
    echo "Usage: $0 <uuid>"
    exit 2
fi

# In 6.5 we supported only taking snapshots of the zoneroot of a joyent brand
# zone, and the snapshots were all just named <snapname>. In SDC7 snapshots
# are named vmsnap-<snapname> when visible to customers, so we need to rename
# these.

parts=$(vmadm lookup -j -o brand,zfs_filesystem uuid=${UUID} | json -a brand zfs_filesystem)
brand=${parts%% *}
zfs_filesystem=${parts##* }

if [[ ${brand} != "joyent" ]]; then
    echo "not converting snapshots for brand ${brand}"
    exit 0
fi

for snap in $(zfs list -t snapshot -Hpo name | grep -v "@vmsnap-" | grep "^${zfs_filesystem}"); do
    snapname=${snap##*@}
    zfs rename ${zfs_filesystem}@${snapname} ${zfs_fileystem}@vmsnap-${snapname}
done

exit 0
