'\" te
.\"
.\" This Source Code Form is subject to the terms of the Mozilla Public
.\" License, v. 2.0. If a copy of the MPL was not distributed with this
.\" file, You can obtain one at http://mozilla.org/MPL/2.0/.
.\"
.TH "sdc\-zfs\-io\-throttle" "1" "June 2011" "" ""
.
.SH "NAME"
\fBsdc-zfs-io-throttle\fR \-\- report on the ZFS I/O throttle
.
.SH "SYNOPSIS"
\fBsdc\-sdc\-zfs\-io\-throttle\fR
.
.SH "DESCRIPTION"
This utility uses dtrace to print information on the calculations and
activity of the ZFS I/O throttle.

.SH "COPYRIGHT"
sdc\-sdc\-zfs\-io\-throttle Copyright (c) 2014, Joyent, Inc\.
