#!/usr/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at http://smartos.org/CDDL
#
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file.
#
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2012, Joyent, Inc. All rights reserved.
#

set -o xtrace

. /lib/svc/share/smf_include.sh
smf_is_globalzone && exit ${SMF_EXIT_OK}

  user_script_exit=${SMF_EXIT_OK}
  if [ -x /var/svc/mdata-user-script ]; then
    /var/svc/mdata-user-script
    [ $? -gt 0 ] && user_script_exit=${SMF_EXIT_ERR_FATAL}
  fi

  # Finish the provisioning process (if the case)

  if [ -f /var/svc/provisioning ]; then
    if [ ${user_script_exit} -eq 0 ]; then
      # If 'provision_ongoing' exists, we assume the user wants to control
      # the final 'success' flag himself and will rename the 'provisioning'
      # file as appropriate. Otherwise, announce success ourselves.
      [ -f /var/svc/provision_ongoing ] || mv /var/svc/provision{ing,_success}
    else
      mv /var/svc/provision{ing,_failure}
    fi
  fi

exit ${user_script_exit}
