#!/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2010-2011 Joyent, Inc.  All rights reserved.
# Use is subject to license terms.

set -o xtrace

. /lib/svc/share/smf_include.sh

PATH=/usr/sbin:/usr/bin; export PATH

case "$1" in
'start')

    if [[ $(zpool list -H | wc -l | tr -d '[:space:]') == "0" ]]; then
        # no zpool yet, can't manage vms on an unsetup compute node.
        /usr/sbin/svcadm disable $SMF_FMRI
        exit $SMF_EXIT_OK
    fi

    if [[ ! $(zfs get -Hpo value name zones/archive 2>&1) == "zones/archive" ]]; then
        # we don't have zones/archive, create it
        mkdir -p /zones/archive
        zfs create -o compression=lzjb -o mountpoint=/zones/archive zones/archive
    fi

    /usr/bin/ctrun -l child -o noorphan /usr/vm/sbin/vmadmd 2>&1 &
    ;;

'stop')
    ;;

*)
    echo "Usage: $0 { start | stop }"
    exit $SMF_EXIT_ERR_FATAL
    ;;
esac
exit $SMF_EXIT_OK
