#!/usr/bin/bash
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2018, Joyent, Inc.
#

#
# This script automates the process of building ISO and USB images of a SmartOS
# build.  It can also be used to produce the proforma disk images used by the
# tools in sdc-headnode.git to produce Triton USB and COAL images.  When
# building SmartOS media, it uses the latest platform file that's been built.
# This program can be invoked standalone via the "gmake iso", "gmake usb" and
# "gmake images" targets of the top-level Makefile in "smartos-live.git".
#
# This script needs to be run either as root or as a user that is granted the
# "Primary Administator" profile.  When run in a non-global zone, it must be
# configured with "fs_allowed=ufs,pcfs"
#
# Things are complicated here by the fact that we would like to run inside a
# non-global zone with older kernels.  Most of our partitioning tools such as
# format do not run well inside a non-global zone, and labeled lofi doesn't
# have sufficient support either.  So we delegate the tricky bits to
# format_image.
#
# Equally, we can no longer directly mount the root partition for populating:
# pcfs has no logic of its own for parsing GPT partitions.  So we have to play
# games using dd(1) to copy the root FS image into the right place based on
# its partition offset.  We also place the partition layout into the images
# tarball, so sdc-headnode can do the same.  (As it is, the offset is actually
# fixed, but that seems like a bad thing to rely on.)
#

bi_console="text"
bi_make_iso=0
bi_proforma_only=0
bi_ufs_root=0
bi_nocleanup=0
bi_imgsz_gb="2"
bi_imgsz=$(( $bi_imgsz_gb * 1000000000 ))
bi_wsroot=
lofi_blkdev=
lofi_rawdev=
esp_blkdev=
usb_image_name=
rootdir=
efimnt=
tmpdir=

function detach_lofi()
{
	local readonly dev=$1

	if [[ -z "$dev" ]]; then
		return
	fi

	if pfexec lofiadm $dev 2>/dev/null; then
		print "Detaching LOFI device $dev ... \c"
		pfexec lofiadm -d $dev
		print "done"
	fi
}

function cleanup()
{
	[[ $bi_nocleanup == 1 ]] && return

	print "Cleaning up"

	if mount | grep $efimnt >/dev/null; then
		pfexec umount $efimnt
	fi

	if mount | grep $rootdir >/dev/null; then
		pfexec umount $rootdir
	fi

	detach_lofi "$lofi_blkdev"
	detach_lofi "$esp_blkdev"

	pfexec rm -f $tmpdir/esp.img
	pfexec rm -f $tmpdir/rootfs.img
	pfexec rm -f $tmpdir/smartos.usb
	pfexec rm -f $tmpdir/partition.map
	pfexec rm -rf $tmpdir/mnt
	pfexec rmdir $tmpdir
}

function fail()
{
        printf "%s\n" "$1" 1>&2
        exit 1
}

function usage()
{
	[[ ! -z $1 ]] && printf "%s\n\n" "$1" 1>&2

	print -u2 "Usage: $0 [-U] [-I] [-x] [-c console] " \
	    "[-p <size>] -r <smartos-live repo>"
	print -u2 "\n -U\tcreate UFS filesystem on root partition (default: PCFS)"
	print -u2 " -I\tbuild SmartOS ISO image (default: USB image)"
	print -u2 " -c\tspecify primary console (e.g. ttyb)"
	print -u2 " -p\tbuild proforma USB image for Triton (e.g. 1gb)"
	print -u2 " -x\tdon't cleanup on exit (for debugging use)\n"
	exit 2
}

function pfrun()
{
	pfexec $*
	local status=$?

	if [[ $status != 0 ]]; then
		print -u2 "\nCommand failed: $*\nExit status: $status"
		exit 1
	fi
}

#
# Construct the EFI System Partition (ESP) image,  We size it at 256 MB, which
# is intentionally much larger than what we need currently, in order to leave
# heaedroom for future projects which may need to store data in the ESP.
#
function create_esp()
{
	local readonly tmpdir=$1
	local readonly efimnt=$2
	local readonly esp_size=256 # MiB
	local readonly esp_sects=$(( $esp_size * 1024 * 1024 / 512 ))

	pfrun mkfile -n ${esp_size}m $tmpdir/esp.img
	esp_blkdev=$(pfexec lofiadm -a $tmpdir/esp.img)
	[[ $? == 0 ]] || fail "Failed to create ESP lofi device"
	readonly esp_rawdev=${esp_blkdev/lofi/rlofi}

	pfrun mkfs -F pcfs -o b=system,size=$esp_sects,nofdisk,fat=32 \
	    $esp_rawdev </dev/null

	pfrun mkdir -p $efimnt
	pfrun mount -F pcfs -o foldcase $esp_blkdev $efimnt
	pfrun mkdir -p $efimnt/efi/boot
	pfrun cp $bi_wsroot/proto.boot/boot/loader64.efi \
	    $efimnt/efi/boot/bootx64.efi
	pfrun umount $efimnt
	pfrun lofiadm -d $esp_blkdev
}

#
# Populate the root filesystem with all the SmartOS bits, as well as the loader
# used in legacy boot mode.
#
function populate_root()
{
	local readonly dir=$1

	print "Installing boot tarball onto root partition ... \c"
	pfexec cp -r $bi_wsroot/proto.boot/* $dir/
	print "done"

	print "Customizing boot loader configuration ... \c"
	readonly shadow="'\$5\$2HOHRnK3\$NvLlm.1KQBbB0WjoP7xcIwGnllhzp2HnT.mDO7DpxYA'"

	case "$bi_console" in
	text)	console="text" ;;
	tty*)	console="$bi_console,text" ;;
	*)	echo "unknown console $bi_console" 2>&1
		exit 1 ;;
	esac

	pfrun touch $dir/boot/loader.conf
	pfrun chmod 666 $dir/boot/loader.conf
	pfrun cat <<EOF >$dir/boot/loader.conf
console="$console"
os_console="$bi_console"
ttya-mode="115200,8,n,1,-"
ttyb-mode="115200,8,n,1,-"
ttyc-mode="115200,8,n,1,-"
ttyd-mode="115200,8,n,1,-"
loader_logo="smartos"
loader_brand="smartos"
root_shadow="${shadow}"
smartos="true"
EOF
	print "done"

	print "Copying platform image to root partition" \
	    "(this will take a while) ... \c"

	pfexec cp -r $bi_wsroot/output/platform-latest/ $dir/platform

	print "done"
}

#
# Build our actual ISO image
#
function create_iso()
{
	local readonly tmpdir=$1
	local readonly iso=$2
	local readonly espimg=$3

	pfrun mkdir -p $bi_wsroot/output-iso
	pfrun mkdir -p $rootdir

	populate_root $rootdir

	pfrun cp $espimg $rootdir/boot/efiboot.img

	pfrun mkisofs -quiet -R \
	    -eltorito-boot boot/cdboot -no-emul-boot -boot-info-table \
	    -eltorito-alt-boot -eltorito-platform efi \
	    -eltorito-boot boot/efiboot.img -no-emul-boot \
	    -o $iso $rootdir

	# FIXME: boot-load-size??
	# FIXME: use -volset and -V ??

	# unused: -N -allow-multidot -cache-inodes -l -U -d -D -volset -V
	# -no-iso-translate
	#
        # $MKISOFS -o "$DIST_ISO" -c .catalog -N -l -R -U \
        #    -allow-multidot -no-iso-translate -cache-inodes -d -D -volset \
        #    "$VOLSETID" -V "$DISTRO_NAME" \
        #    -eltorito-boot boot/cdboot -no-emul-boot -boot-info-table \
        #    -eltorito-alt-boot \
        #    -eltorito-platform efi \
        #    -eltorito-boot boot/efiboot.img -no-emul-boot \
        #    "$PKG_IMG_PATH"

	#isopath="$bi_output_dir/$bi_platform_name.iso"
	#LC_ALL=C mkisofs -R -b 		\
	#    boot/grub/stage2_eltorito	\
	#    -no-emul-boot 		\
	#    -boot-load-size 4		\
	#    -boot-info-table		\
	#    -quiet			\
	#    -o 	$isopath		\
	#    $bi_tmpdir/ >/dev/null

	print "Successfully created $iso"
}

#
# Assemble all our boot parts into the disk image (the root partition is copied
# over later).
#
function create_image()
{
	local readonly tmpdir=$1
	local readonly size=$2
	local readonly file=$3

	pfrun mkfile -n $size $file

	lofi_blkdev=$(pfexec lofiadm -a $file)
	[[ $? == 0 ]] || fail "Failed to create lofi device"

	pfrun $bi_wsroot/tools/format_image/format_image \
	    -m $bi_wsroot/proto.boot/boot/pmbr \
	    -b $bi_wsroot/proto.boot/boot/gptzfsboot -e $tmpdir/esp.img \
	    -o ${lofi_blkdev/lofi/rlofi} >$tmpdir/partition.map

	pfrun lofiadm -d $lofi_blkdev
}

#
# Create the blank root filesystem.
#
function create_root()
{
	local readonly dev=$1
	local readonly image=$2
	local readonly offset=$3
	local readonly sects=$(( $4 / 512 ))

	if [[ $bi_ufs_root == 1 ]]; then
		print "Creating UFS filesystem in root partition ... \c"
		pfexec newfs $dev </dev/null
	else
		print "Creating PCFS filesystem in root partition ... \c"
		pfrun mkfs -F pcfs -o b=SMARTOSBOOT,size=$sects,nofdisk,fat=32 \
		    $dev </dev/null
	fi

	print "done"

	if [[ $bi_proforma_only == 1 ]]; then
		return
	fi
}

#
# Copy the root filesystem image into the correct place inside the image.
#
function copy_root()
{
	local readonly dev=$1
	local readonly image=$2
	local readonly offset=$3
	local readonly bs=1048576

	print "Copying root filesystem ..."
	pfrun /usr/bin/dd bs=$bs conv=notrunc if=$dev of=$image \
	    oseek=$(( $offset / $bs )) >/dev/null
	print "done"
}

#
#
function mount_root()
{
	local readonly dev=$1
	local readonly rootmnt=$2
	local mntopts="-F pcfs"

	if [[ $bi_ufs_root == 1 ]]; then
		mntopts="-o nologging"
	fi

	print "Mounting root partition at $rootmnt ... \c"
	pfrun mkdir -p $rootmnt
	pfrun mount $mntopts $dev $rootmnt 2>/dev/null
	print "done"
}

function copy_results()
{
	local readonly outdir=$1
	local readonly outfile=$2
	local readonly prefix=$3
	local readonly uid=$(id -u)
	local readonly gid=$(id -g)

	mkdir -p $outdir
	pfrun mv $tmpdir/smartos.usb $outdir/$outfile
	pfrun chmod 644 $outdir/$outfile
	pfrun chown ${uid}:${gid} $outdir/$outfile
	pfrun cp $tmpdir/partition.map $outdir/${prefix}partition.map
	pfrun chown ${uid}:${gid} $outdir/${prefix}partition.map
	print "Successfully created $outdir/$outfile"
}

while getopts "IUc:p:r:x" c $@; do
	case "$c" in
	I)	bi_make_iso=1 ;;
	U)	bi_ufs_root=1 ;;
	c)	bi_console=${OPTARG} ;;
	p)	bi_proforma_only=1
		bi_imgsz_gb=${OPTARG%gb}
		bi_imgsz=$(( $bi_imgsz_gb * 1000000000 )) ;;
	r)	bi_wsroot=$(readlink -f $OPTARG) ;;
	x)	bi_nocleanup=1 ;;
	:)	usage ;;
	*)	usage ;;
	esac
done

set -eou pipefail
export SHELLOPTS

[[ -z "$bi_wsroot" ]] && usage "-r is required"

[[ $bi_proforma_only == 1 ]] && [[ $bi_ufs_root == 1 ]] && \
    usage "-p and -U are mutually exclusive"

[[ $bi_proforma_only == 1 ]] && [[ $bi_make_iso == 1 ]] && \
    usage "-p and -I are mutually exclusive"

[[ -e $bi_wsroot/output/platform-latest ]] || \
    fail "No platform image found in $bi_wsroot/output"


tmpdir=$(mktemp -d -p /var/tmp) || fail "mktemp failed!"

trap cleanup EXIT

efimnt=$tmpdir/mnt/efi
rootdir=$tmpdir/mnt/root
usb_image_name=$(readlink -f $bi_wsroot/output/platform-latest)
usb_image_name=$(basename $usb_image_name)
iso_image_name="$bi_wsroot/output-iso/${usb_image_name}.iso"
usb_image_name="${usb_image_name}.usb"

print "Creating EFI System Partition image ... \c"
create_esp $tmpdir $efimnt
print "done"

if [[  $bi_make_iso == 1 ]]; then
	create_iso $tmpdir $iso_image_name $tmpdir/esp.img
	exit 0
fi

print "Creating $bi_imgsz_gb GB image at $tmpdir/smartos.usb ... \c"
create_image $tmpdir $bi_imgsz $tmpdir/smartos.usb
print "done"

echo "partition.map:"
cat $tmpdir/partition.map

rootoff=$(nawk '$1 == "root" { print $3 }' <$tmpdir/partition.map)
rootsize=$(nawk '$1 == "root" { print $4 }' <$tmpdir/partition.map)

pfrun mkfile -n $rootsize $tmpdir/rootfs.img

lofi_blkdev=$(pfexec lofiadm -a $tmpdir/rootfs.img)
[[ $? == 0 ]] || fail "Failed to create lofi device"

lofi_rawdev=${lofi_blkdev/lofi/rlofi}

create_root $lofi_rawdev $tmpdir/smartos.usb $rootoff $rootsize

#
# The proforma image's root partition is populated by sdc-headnode, not us.
#
if [[ $bi_proforma_only != 1 ]]; then
	mount_root $lofi_blkdev $rootdir
	populate_root $rootdir
	pfrun umount $rootdir
fi

copy_root $lofi_rawdev $tmpdir/smartos.usb $rootoff

pfrun lofiadm -d $lofi_blkdev

if [[ $bi_proforma_only == 1 ]]; then
	copy_results $bi_wsroot/proto.images ${bi_imgsz_gb}gb.img ${bi_imgsz_gb}gb.
else
	copy_results $bi_wsroot/output-usb $usb_image_name ""
fi

exit 0
