#!/usr/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2013 Joyent, Inc.  All rights reserved.

shopt -s xpg_echo

#
# Someone may have set an alias, let's just get rid of them all for this shell.
#
unalias -a

bm_arg0=$(basename $0)

function fail
{
	local msg="$*"
	[[ -z "$msg" ]] && msg="failed"
	echo "$bm_arg0: $msg" >&2
	exit 1
}

function validate
{
	local count
	[[ ! -d $bm_mdir ]] && \
	    fail "manifest snippet directory doesn't exist: $bm_mdir"

	count=$(ls $bm_mdir | wc -l)
	[[ $? -eq 0 ]] || fail "ls and wc inexplicably failed"
	[[ $count -gt 0 ]] || fail "no files in $bm_mdir"
}

function build
{
	for file in $bm_mdir/*; do
		echo "Adding manifest files from $file... \c " >&2
		grep -v "^#" $file
		[[ $? -eq 0 ]] || fail "failed to append to manifest"
		echo "done" >&2
	done
	[[ $? -eq 0 ]] || fail "failed to remove comments from manifest"
}

if [[ -z "$1" ]]; then
	fail "Manifest directory is required"
fi

bm_mdir=$1

validate
build
exit 0
