#!/usr/bin/env bash
#
# Copyright (c) 2012 Joyent Inc.
#

# Setup for building stuff!
unset CC
unset CXX
ROOT=`pwd`
export PATH=/opt/onbld/bin:/sbin:/usr/sbin:/usr/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/opt/local/bin

if [[ -z $BUILDSTAMP ]]; then
  BUILDSTAMP=`TZ=UTC date "+%Y%m%dT%H%M%SZ"`; export BUILDSTAMP
fi
mkdir -p ${ROOT}/proto
echo ${BUILDSTAMP} > ${ROOT}/proto/buildstamp

echo "==> Building Illumos (${BUILDSTAMP})"

set -o pipefail
set -e

cd ${ROOT}/projects/illumos
[[ -d "log" ]] || mkdir -p log
cp usr/src/tools/scripts/nightly.sh ./nightly
chmod u+x ./nightly
gsed -i -e "s|^GATE=.*$|GATE=\"joyent_${BUILDSTAMP}\"; export GATE|" illumos.sh

ksh93 ./usr/src/tools/scripts/bldenv.sh illumos.sh \
    'cd $CODEMGR_WS/usr/src && export PATH="$PATH:/opt/local/bin" && \
    dmake setup && cd tools && dmake install'

time ./nightly illumos.sh
res=$?
# Post-build joyent specific changes to the proto area

# "has bin" man pages are put under usr/has which we don't deliver.  Move
# the required man page to the right place.
rm -f ${ROOT}/proto/usr/share/man/man1/edit.1
mv ${ROOT}/proto/usr/has/man/man1has/edit.1has \
   ${ROOT}/proto/usr/share/man/man1/edit.1

exit $res
