#!/usr/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2011, Joyent, Inc.

shopt -s xpg_echo

#
# Someone may have set an alias, let's just get rid of them all for this shell.
#
unalias -a

bm_arg0=$(basename $0)
bm_root=$(dirname $0)/..
bm_mdir=$bm_root/manifest.d
bm_man=$bm_root/manifest.gen

function fail
{
	local msg="$*"
	[[ -z "$msg" ]] && msg="failed"
	echo "$bm_arg0: $msg" >&2
	exit 1
}

function validate
{
	local count
	[[ -f $bm_man ]] && \
	    fail "manifest file already exists: $bm_man"
	[[ ! -d $bm_mdir ]] && \
	    fail "manifest snippet directory doesn't exist: $bm_mdir"

	count=$(ls $bm_mdir | wc -l)
	[[ $? -eq 0 ]] || fail "ls and wc inexplicably failed"
	[[ $count -gt 0 ]] || fail "no files in $bm_mdir"
}

function build
{
	touch $bm_man || fail "failed to create $bm_man"	
	for file in $bm_mdir/*; do
		echo "Adding manifest files from $file... \c "
		cat $file >> $bm_man
		[[ $? -eq 0 ]] || fail "failed to append to manifest"
		echo "done"
	done
	grep -v "^#" < $bm_man > $bm_man.tmp
	[[ $? -eq 0 ]] || fail "failed to remove comments from manifest"
	mv -f $bm_man.tmp $bm_man
}

validate
build
exit 0
