#!/bin/bash
#
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2013, Joyent, Inc. All rights reserved.
# Copyright (c) 2014 Elysium Digital, L.L.C.
#

#
# Generates the SmartOS vmware image
#

shopt -s xpg_echo
set -o pipefail
export PATH=/usr/bin:/opt/local/bin

function fail
{
	local msg="$*"
	[[ -z "$msg" ]] && msg="failed"
	exit 1
}

cd $(dirname $0)/.. || fail "failed to cd to $(dirname $0)"

[[ -f output/buildstamp ]] || fail "failed to find output/buildstamp"
buildstamp="$(cat output/buildstamp)"
usb_image="output-usb/platform-${buildstamp}.usb.bz2"

echo "Looking for USB image..."
if [[ ! -f ${usb_image} ]]; then
	echo "Building USB image to embed in vmware image..."
	(tools/build_usb) || fail "Failed to build USB image"
fi

[[ -f ${usb_image} ]] || fail "failed to find ${usb_image}"
echo "Using ${usb_image}..."

echo "Creating output-vmware/ ..."
mkdir -p output-vmware || fail "failed to create output-vmware"

if [[ -d output-vmware/SmartOS.vmwarevm ]]; then
	echo "Removing existing template..."
	rm -r output-vmware/SmartOS.vmwarevm || \
	    fail "failed to remove existing template directory"
fi
echo "Copying vmware template into place..."
cp -r tools/SmartOS.vmwarevm/ output-vmware/ || \
    fail "failed to copy vmware template"

echo "Copying USB image into place..."
bzip2 -d < output-usb/platform-${buildstamp}.usb.bz2 \
    > output-vmware/SmartOS.vmwarevm/smartos.img || \
    fail "failed to decompress output-usb/platform-${buildstamp}.usb.bz2"
echo "Creating compressed tarball suitable for upload..."
(cd output-vmware && \
    gtar -jcf smartos-${buildstamp}.vmwarevm.tar.bz2 SmartOS.vmwarevm) || \
    fail "failed creating output-vmware/smartos-${buildstamp}.vmwarevm.tar.bz2"
echo "Done!"
