#!/usr/bin/env bash
#
# Copyright (c) 2010 Joyent Inc.
#

# Setup for building stuff!
unset CC
unset CXX
ROOT=`pwd`
export PATH=/opt/onbld/bin:/sbin:/usr/sbin:/usr/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/opt/local/bin

BUILDSTAMP=`TZ=UTC date "+%Y%m%dT%H%M%SZ"`; export BUILDSTAMP
mkdir -p ${ROOT}/proto
echo ${BUILDSTAMP} > ${ROOT}/proto/buildstamp

echo "==> Building Illumos (${BUILDSTAMP})"

set -o pipefail
set -e

cd ${ROOT}/projects/illumos
cp usr/src/tools/scripts/nightly.sh ./nightly
chmod u+x ./nightly
gsed -i -e "s|^GATE=.*$|GATE=\"joyent_${BUILDSTAMP}\"; export GATE|" illumos.sh
ksh93 ./usr/src/tools/scripts/bldenv.sh -d illumos.sh 'cd $CODEMGR_WS/usr/src && export PATH="$PATH:/opt/local/bin" && dmake setup && cd tools && dmake install'
time ./nightly illumos.sh
res=$?

exit $res
