#!/bin/bash

if [ -z "${BUILDSTAMP}" ]; then
  #BUILDSTAMP=`TZ=UTC date "+%Y-%m-%dT%H:%M:%SZ"`
  BUILDSTAMP=`TZ=UTC date "+%Y%m%dT%H%M%SZ"`
fi

rdmnt=$1
if [ -z "${rdmnt}" ]; then
  echo "Usage: $0 <rdmnt directory>"
  exit 1
fi

echo "Customizing ${rdmnt}"
pfexec cp /dev/null ${rdmnt}/etc/mnttab
pfexec cp /dev/null ${rdmnt}/var/log/syslog
pfexec cp /dev/null ${rdmnt}/var/adm/wtmpx
pfexec chown root:root ${rdmnt}
echo "${BUILDSTAMP}" | pfexec tee ${rdmnt}/etc/joyent_buildstamp >/dev/null 2>&1
pfexec gsed -i -e "s/ [0-9]\{8\}T[0-9]\{6\}Z/ ${BUILDSTAMP}/" ${rdmnt}/etc/motd
pfexec gsed -i -e "s/ [0-9]\{8\}T[0-9]\{6\}Z/ ${BUILDSTAMP}/" ${rdmnt}/etc/issue

exit 0
