#!/usr/bin/python
#
# Takes a 'manifest' style file and outputs a sorted version, warning about
# any duplicates.
#

import os
import sys
files = dict()
filename = 'manifest'

# if filename is passed as first argument, use that file instead
if len(sys.argv) >= 2 and os.path.isfile(sys.argv[1]):
    filename = sys.argv[1]

for line in open(filename).readlines():
    line=line.lstrip()
    if len(line) == 0 or line[0] == '#':
       next
    fields = line.rstrip().split(' ')
    if fields[1] in files:
        print >> sys.stderr, "WARNING: duplicate entry for '%s'" % (fields[1])
    files[fields[1]] = line.rstrip('\n')

k = files.keys()
ks = k.sort()
for key in k:
    print files[key].rstrip(' ')
