#!/usr/bin/python
#
# Takes a 'manifest' style file and outputs a sorted version, warning about
# any duplicates.
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at COPYING
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at COPYING.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2010,2011 Joyent Inc.
#


import os
import sys
files = dict()
filename = 'manifest'

# if filename is passed as first argument, use that file instead
if len(sys.argv) >= 2 and os.path.isfile(sys.argv[1]):
    filename = sys.argv[1]

for line in open(filename).readlines():
    line=line.lstrip()
    if len(line) == 0 or line[0] == '#':
       next
    fields = line.rstrip().split(' ')
    if fields[1] in files:
        print >> sys.stderr, "WARNING: duplicate entry for '%s'" % (fields[1])
    files[fields[1]] = line.rstrip('\n')

k = files.keys()
ks = k.sort()
for key in k:
    print files[key].rstrip(' ')
