#!/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

#
# Since this script is grabbing data from a system in a potentially unknown
# state we don't use 'set -o errexit' here because we don't want to fail to
# grab other data when we fail to grab data from one source.
#

# Note for man page. Use this to generate the list of available args to "-c":
#   grep ^function sdc-sbcreate | grep grab_ | cut -c 15- | grep -v default | sort

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/smartdc/bin:/opt/local/bin:/opt/local/sbin

. /lib/sdc/config.sh
load_sdc_config

OS=$(uname -s)

function usage
{
    echo "Usage: `basename $0` [-d dir] [-o output] [-c content] [-n <compute node>] [-iu]"
    usage=/tmp/usage.$$

    #
    # Some things are just worth doing properly.
    #
    cat > $usage <<EOF
        BEGIN { p = indent = 8; printf("%*s", p - 1, ""); }
        {
            l = length($1) + 1;
            if (p + l >= 80) {
                printf("\n%*s%s", indent, "", \$1);
                p = indent + l;
            } else {
                printf(" %s", \$1);
                p += l;
            }
        }
        END { printf("\n"); }
EOF

    echo "  'content' must be one or more of:"
    compgen -A function grab_ | cut -d_ -f2- | nawk -f $usage
    rm $usage
    exit 1
}

function fatal
{
    echo "`basename $0`: $*"
    exit 1
}

function do_countdown
{
    echo ""
    echo "This tool will create an SDC support bundle in `dirname $TEMPDIR`."
    echo "This may take some time...  If you wish to abort press CTRL-C now!"
    echo ""
    countdown=$((${COUNTDOWN} - 1))
    while [[ ${countdown} -ge 0 ]]; do
        printf "                                   \r"
        printf "Starting in ${countdown} seconds...\r"
        sleep 1
        countdown=$((${countdown} - 1))
    done
    echo ""
    echo ""
}

function grab_default
{
    #
    # By default, we grab everything except for compute nodes.
    #
    grab_sysinfo
    grab_meminfo
    grab_cpuinfo
    grab_dlinfo
    grab_ifconfig
    grab_routes
    grab_auditlog
    grab_svcs
    grab_ps
    grab_zfsinfo
    grab_df
    grab_modinfo
    grab_headnode_info
    grab_zoneinfo
    grab_zoneconfigs
    grab_vmconfigs
    grab_zonelogs
    grab_cores
    grab_dumps
    grab_fmdump
    grab_logs
    grab_castatus
    grab_phonehome
    grab_platform_md5
    grab_app_config
    grab_fmd
    grab_disk_list
    grab_zpool_history
    grab_rabbitmq_info
}

function grab_sysinfo
{
    echo "  > sysinfo"
    sysinfo > ${TEMPDIR}/sysinfo.json
}

function grab_meminfo
{
    if [[ ${OS} == "Linux" ]]; then
        echo "  > meminfo"
        cat /proc/meminfo > ${TEMPDIR}/meminfo
    fi
}

function grab_cpuinfo
{
    if [[ ${OS} == "Linux" ]]; then
        echo "  > cpuinfo"
        cat /proc/cpuinfo > ${TEMPDIR}/cpuinfo
    fi
}

function grab_dlinfo
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > datalink info"
        dladm show-phys -m > ${TEMPDIR}/dladm.phys
        dladm show-vnic > ${TEMPDIR}/dladm.vnic
        dladm show-linkprop > ${TEMPDIR}/dladm.linkprop
        dladm show-bridge > ${TEMPDIR}/dladm.bridge
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > datalink info"
        for eth in $(ifconfig -a | grep "^eth[0-9]* " | cut -d' ' -f1); do
            ethtool ${eth} > ${TEMPDIR}/ethtool.${eth}
            ethtool -S ${eth} >> ${TEMPDIR}/ethtool.${eth}
        done
    fi
}

function grab_ifconfig
{
    echo "  > network interface info"
    ifconfig -a > ${TEMPDIR}/ifconfig.a
}

function grab_routes
{
    echo "  > routing table"
    netstat -rn > ${TEMPDIR}/netstat.rn
}

function grab_auditlog
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > auditlog info"
        (cd /var/audit && tar -zcvf ${TEMPDIR}/var.audit.tar.gz .) >&4 2>&1
    fi
}

function grab_svcs
{
    echo "  > services"
    echo "    (all services)"
    if [[ ${OS} == "SunOS" ]]; then
        svcs -Z -a > ${TEMPDIR}/svcs.all
        mkdir ${TEMPDIR}/svccfg_archive
        echo "    (global service archive)"
        svccfg archive | gzip -c > ${TEMPDIR}/svccfg_archive/global.gz
        if [[ -d /usbkey/zones ]]; then
            for zone in $(cd /usbkey/zones ; ls); do
                echo "    (service archive for $zone)"
                zlogin ${zone} svccfg archive \
                | gzip -c > ${TEMPDIR}/svccfg_archive/${zone}.gz
            done
        fi
    elif [[ ${OS} == "Linux" ]]; then
        initctl list > ${TEMPDIR}/initctl.list
    fi
}

function grab_ps
{
    echo "  > process information"
    if [[ ${OS} == "SunOS"  ]]; then
        ps -efZ > ${TEMPDIR}/ps.efZ
    elif [[ ${OS} == "Linux" ]]; then
        ps -eLfwlyF > ${TEMPDIR}/ps.eLfwlyF
    fi
}

function grab_zfsinfo
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > zfs info"
        echo "    (zpool status)"
        zpool status -v > ${TEMPDIR}/zpool.status
        echo "    (zfs list)"
        zfs list -t all > ${TEMPDIR}/zfs.list
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > LVM info"
        echo "    (pvs)"
        pvs -v --all > ${TEMPDIR}/lvm.pvs 2>/dev/null
        echo "    (vgs)"
        vgs -v --all > ${TEMPDIR}/lvm.vgs 2>/dev/null
        echo "    (lvs)"
        lvs -v --all > ${TEMPDIR}/lvm.lvs 2>/dev/null
    fi
}

function grab_app_config
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > app zone config"
        zones=$(zoneadm list -i | grep -v global)
        for zone in ${zones}; do
          if [[ -d /zones/${zone}/root/opt/smartdc/${zone}-data/config ]]; then
             ( cd  /zones/${zone}/root/opt/smartdc/${zone}-data/; /usr/bin/gtar -zcf ${TEMPDIR}/${zone}.config.tgz config )
          fi
        done
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > skipping zone info on Linux"
    fi
}

function grab_disk_list
{
    echo "  > disk list"
    if [[ ${OS} == "SunOS" ]]; then
        /usr/bin/disklist -a > ${TEMPDIR}/disklist
    elif [[ ${OS} == "Linux" ]]; then
        /sbin/fdisk -lu > ${TEMPDIR}/disklist 2>/dev/null
    fi
}

function grab_zpool_history
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > zpool history"
        zpool history > ${TEMPDIR}/zpool.history
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > skipping zpool history on Linux"
    fi
}

function grab_fmd
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > fmd"
        (cd /var/fm ; /usr/bin/gtar -zcf ${TEMPDIR}/fmd.tgz fmd)
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > skipping fmd logs on Linux"
    fi
}

function grab_df
{
    echo "  > disk utilization"
    df > ${TEMPDIR}/df
}

function grab_modinfo
{
    echo "  > module information"
    if [[ ${OS} == "SunOS" ]]; then
        modinfo -w > ${TEMPDIR}/modinfo
    elif [[ ${OS} == "Linux" ]]; then
        lsmod > ${TEMPDIR}/lsmod
    fi
}

function grab_headnode_info
{
    if [[ -d /usbkey ]]; then
        find /usbkey -ls > ${TEMPDIR}/usbkey.filelist
        echo "  > usbkey filelist"
        tar -cvf ${TEMPDIR}/usbkey.config.tar usbkey/config* >&4 2>&1
    fi
}

function grab_zoneinfo
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > zone list"
        zoneadm list -v -c > ${TEMPDIR}/zonelist.vc
        echo "  > zone kernel state"
        zonemon -k > ${TEMPDIR}/zonekstate
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > skipping zone info on Linux"
    fi
}

function grab_zoneconfigs
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > zone configs"
        tar -cvf ${TEMPDIR}/zone.configs.tar etc/zones >&4 2>&1
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > skipping zone configs on Linux"
    fi
}

function grab_vmconfigs
{
    if [[ -d /etc/vms ]]; then
        echo "  > VM configs"
        tar -cvf ${TEMPDIR}/vm.configs.tar etc/vms >&4 2>&1
    fi
}

function grab_zonelogs
{
    if [[ -n $headnode ]]; then
        echo "  > zone logs"
        tar -zcvf ${TEMPDIR}/zone.logs.tar.gz zones/*/root/var/svc/log \
            zones/*/root/opt/smartdc/*/log >&4 2>&1
    fi
}

function grab_cores
{
    if [[ -n $headnode ]]; then
        echo "  > cores"
        tar -zcvf ${TEMPDIR}/cores.tar.gz zones/*/cores >&4 2>&1
    fi
}

function grab_dumps
{
    if [[ ${OS} == "SunOS" ]]; then
        # These are already compressed
        echo "  > kernel crash dumps"
        tar -cvf ${TEMPDIR}/dumps.tar var/crash/volatile >&4 2>&1
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > skipping kernel crash dumps on Linux"
    fi
}

function grab_fmdump
{
    if [[ ${OS} == "SunOS" ]]; then
        echo "  > fmdump"
        fmdump > ${TEMPDIR}/fmdump.out
        fmdump -e > ${TEMPDIR}/fmdump.e.out
    elif [[ ${OS} == "Linux" ]]; then
        echo "  > skipping kernel crash dumps on Linux"
    fi
}

function grab_logs
{
    echo "  > logs"
    if [[ ${OS} == "SunOS" ]]; then
       tar -zcvf ${TEMPDIR}/gz-logs.tar.gz var/svc/log \
           etc/svc/volatile var/adm >&4 2>&1
    elif [[ ${OS} == "Linux" ]]; then
       tar -zcvf ${TEMPDIR}/host-logs.tar.gz var/log >&4 2>&1
    fi
}

function grab_castatus
{
    if [[ ${OS} == "SunOS" && -n ${CONFIG_ca_admin_ip} ]]; then
        curl http://${CONFIG_ca_admin_ip}:23181/ca/admin/status?recurse=true >&4 2>&1 \
        | json > ${TEMPDIR}/ca.status
    fi
}

function grab_phonehome
{
    if [[ -d /opt/smartdc/phonehome ]]; then
        tar -zcvf ${TEMPDIR}/phonehome.tar.gz opt/smartdc/phonehome >&4 2>&1
    fi
}

function grab_compute
{
    if [[ $headnode != "true" ]]; then
        return
    fi

    local oneach=/smartdc/bin/sdc-oneachnode
    local outfile=/var/tmp/bundle.$$
    local destdir=$TEMPDIR/compute-nodes
    local curdir=`pwd`
    local opts="-io $outfile"
    local file

    if [[ -n $opt_n ]]; then
        oneach="$oneach -n $opt_n"
        if ! $oneach -t 10 date >&4 2>&1 ; then
             fatal "node $opt_n is invalid or not responding"
        fi
    fi

    mkdir -p $destdir

    if [[ -z $opt_n ]]; then
        echo "  > compute nodes"
    else
        echo "  > node $opt_n"
    fi

    #
    # First, generate the bundles
    #
    echo "    (remote bundle generation)"
    $oneach -cv -t 10 -T 1800 /smartdc/bin/sdc-sbcreate -c $opt_c $opts >&4 2>&1

    #
    # Now copy the bundles...
    #
    echo "    (remote bundle collection)"
    $oneach -cv -t 10 -T 1800 -f $outfile -d $destdir >&4 2>&1

    #
    # ...expand them...
    #
    echo "    (remote bundle expansion)"

    cd $destdir
    for file in `ls -1`; do
        mv $file $file.tar.bz2 >&4 2>&1
        bzip2 -d -c $file.tar.bz2 2>&4 | tar xvf - >&4 2>&1
        rm $file.tar.bz2 >&4 2>&1
    done
    cd $curdir
 
    #
    # ...and blow them away.
    #
    echo "    (remote bundle destruction)"
    $oneach -cv -t 10 -T 30 rm $outfile >&4 2>&1
}

function grab_platform_md5
{
    if [[ $headnode != "true" ]]; then
        return
    fi

    echo "  > kernel & platform integrity hash"
    sum -R -x md5 /usbkey/os > ${TEMPDIR}/platforms_cache.md5 
    /usbkey/scripts/mount-usb.sh
    sum -R -x md5 /mnt/usbkey/os > ${TEMPDIR}/platforms_bootable.md5
}

function grab_rabbitmq_info
{
    if [[ $headnode != "true" ]]; then
        return
    fi

    echo "  > rabbitmq status"

    rbout=${TEMPDIR}/rabbitmq.list
    rbcmd=/opt/local/sbin/rabbitmqctl

    rbstatus=`zoneadm -z rabbitmq list -p 2>&1 | cut -d: -f3`
    if [ $? -eq 0 -a "$rbstatus" == "running" ]; then
        zlogin rabbitmq $rbcmd list_queues > $rbout
        echo >>$rbout
        zlogin rabbitmq $rbcmd list_exchanges >> $rbout
        echo >>$rbout
        zlogin rabbitmq $rbcmd list_bindings >> $rbout
        echo >>$rbout
        zlogin rabbitmq $rbcmd list_connections >> $rbout
        echo >>$rbout
        zlogin rabbitmq $rbcmd list_channels >> $rbout
        echo >>$rbout
        zlogin rabbitmq $rbcmd list_consumers >> $rbout
    else
        echo "No rabbitmq zone or zone not running" >$rbout
    fi
}

while getopts "d:o:c:in:u" opt; do
    if [[ "$opt" == "?" ]]; then
        usage
    fi

    varname=opt_${opt}

    if [[ -z $OPTARG ]]; then
        eval $varname=true
    else
        eval $varname=\$OPTARG
    fi
done

if [[ -n ${opt_n} && ${headnode} != "true" ]]; then
    fatal "can only specify -n flag when running on a headnode"
fi

if [[ -n $opt_c ]]; then
    contents=`echo $opt_c | tr ',' ' '`

    # ensure -c didn't include 'default' and anything other than 'compute'
    contents_count=$(echo ${contents} | wc -w | tr -d '[:space:]')
    if echo " ${contents} " | grep " default " >/dev/null; then
        if [[ ${contents_count} -gt 2 ]]; then
            fatal "cannot specify default and contents included by default"
        elif [[ ${contents_count} -eq 2 ]] && \
            ! echo " ${contents} " | grep " compute " >/dev/null; then
            fatal "cannot specify default and contents included by default"
        fi
    fi

    opt_c=
    for content in $contents; do
        if ! compgen -A function grab_ | \
          grep "^grab_${content}\$" 1> /dev/null ; then
            echo "`basename $0`: unrecognized content '$content'"
            usage
        fi
        if [[ $content != "compute" ]]; then
            opt_c=${opt_c}${content},
        elif [[ -n $opt_n ]]; then
            fatal "cannot specify both node and 'compute' content"
        elif [[ ${headnode} != "true" ]]; then
            fatal "can only specify 'compute' content on a headnode"
        fi
    done

    if [[ -z $opt_c ]]; then
        fatal "must additionally specify content to gather from compute nodes"
    fi
elif [[ -n $opt_n ]]; then
    fatal "must specify content when node is specified"
fi

# Need the output dir first.
BASEDIR=${opt_d:-/var/tmp}
if [[ ${BASEDIR:0:1} != "/" ]]; then
    BASEDIR=`pwd`/$BASEDIR
fi
TEMPDIR=$BASEDIR/sdcsb.$$/`sysinfo | json UUID`
LOGFILE=$BASEDIR/sdcsb.$$.log
FILENAME=sdc-support.$(hostname).$(TZ=UTC date "+%Y%m%dT%H%M%SZ").tar.bz
OUTFILE=${opt_o}
if [[ -z "${OUTFILE}" ]]; then
    OUTFILE=$BASEDIR/$FILENAME
elif [[ ${OUTFILE:0:1} != "/" ]]; then
    OUTFILE=$BASEDIR/$OUTFILE
fi
COUNTDOWN=5

if [[ -z $opt_i ]]; then
    #
    # If the user has not specified immediate operation (-i), give them a
    # sanity pause before beginning -- this script can take some time and
    # write a lot of data.
    do_countdown
fi

if [[ "$(sysinfo | json 'Boot Parameters'.headnode)" == "true" ]]; then
    headnode=true
fi

mkdir -p ${TEMPDIR}

exec 4>${LOGFILE}
export BASH_XTRACEFD=4
export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o xtrace

echo "==> Gathering System Information"

cd /

if [[ -z $opt_c ]]; then 
    grab_default
elif [[ -n $opt_n ]]; then
    grab_compute
else
    for content in $contents; do
        eval grab_${content}
    done
fi

echo "==> packing data to ${OUTFILE}"
( cd ${TEMPDIR}/.. && tar -jcvf ${OUTFILE} `basename ${TEMPDIR}` >&4 2>&1 )
mv ${LOGFILE} ${OUTFILE}.log

echo "==> cleaning up"
rm -rf `dirname ${TEMPDIR}`

if [[ -n $opt_u ]]; then
    echo "==> uploading to Joyent support"
    /smartdc/bin/sdc-sbupload ${OUTFILE}
fi

echo "==> done"
