#!/bin/ksh -p
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
# Copyright 2014 Joyent, Inc.  All rights reserved.
#

# Restrict executables to /bin, /usr/bin, /usr/sbin and /usr/sfw/bin
PATH=/bin:/usr/bin:/usr/sbin:/usr/sfw/bin

export PATH

# Setup i18n output
TEXTDOMAIN="SUNW_OST_OSCMD"
export TEXTDOMAIN

# Log passed arguments to file descriptor 2
log()
{
	[[ -n $logfile ]] && echo "$@" >&2
}

#
# Send the provided printf()-style arguments to the screen and to the
# logfile.
#
screenlog()
{
	typeset fmt="$1"
	shift

	printf "$fmt\n" "$@"
	[[ -n $logfile ]] && printf "$fmt\n" "$@" >&2
}

# Print and log provided text if the shell variable "verbose_mode" is set
verbose()
{
	[[ -n $verbose_mode ]] && echo "$@"
	[[ -n $logfile ]] && [[ -n $verbose_mode ]] && echo "$@" >&2
}

cmd_not_found=$(gettext "Required command '%s' cannot be found!")
cmd_not_exec=$(gettext "Required command '%s' not executable!")
zone_initfail=$(gettext "Attempt to initialize zone '%s' FAILED.")
path_abs=$(gettext "Pathname specified to -d '%s' must be absolute.")

cmd=$(gettext "%s -z <zone name> %s")

both_modes=$(gettext "%s: error: cannot select both silent and verbose modes")

not_found=$(gettext "%s: error: file or directory not found.")

wrong_type=\
$(gettext "%s: error: must be a gzip, bzip2, .Z or uncompressed tar archive.")

not_readable=$(gettext "Cannot read file '%s'")

no_install=$(gettext "Could not create install directory '%s'")
no_log=$(gettext "Could not create log directory '%s'")
no_logfile=$(gettext "Could not create log file '%s'")

root_full=$(gettext "Zonepath root %s exists and contains data; remove or move aside prior to install.")

install_zone=$(gettext "Installing zone '%s' at root directory '%s'")
install_from=$(gettext "from archive '%s'")

install_fail=$(gettext "Installation of zone '%s' FAILED.")
see_log=$(gettext "See the log file:\n  '%s'\nfor details.")

install_abort=$(gettext "Installation of zone '%s' aborted.")
install_good=$(gettext "Installation of zone '%s' completed successfully.")

# Clean up on interrupt
trap_cleanup()
{
	msg="Installation cancelled due to interrupt."

	screenlog "$msg"
	exit $int_code
}

usage()
{
	int_code=$ZONE_SUBPROC_USAGE

	echo $(gettext "Usage:")
	printf "  $cmd\n" "zoneadm" "install [-s|-v] -d {path to archive}"

	echo

	exit $int_code
}

#
# The main body of the script starts here.
#
# This script should never be called directly by a user but rather should
# only be called by zoneadm to install a lx-branded zone.
#

#
# Exit values used by the script, as #defined in <sys/zone.h>
#
#	ZONE_SUBPROC_OK
#	===============
#	Installation was successful
#
#	ZONE_SUBPROC_USAGE
#	==================
#	Improper arguments were passed, so print a usage message before exiting
#
#	ZONE_SUBPROC_NOTCOMPLETE
#	========================
#	Installation did not complete, but another installation attempt can be
#	made without an uninstall
#
#	ZONE_SUBPROC_FATAL
#	==================
#	Installation failed and an uninstall will be required before another
#	install can be attempted
#
ZONE_SUBPROC_OK=0
ZONE_SUBPROC_USAGE=253
ZONE_SUBPROC_NOTCOMPLETE=254
ZONE_SUBPROC_FATAL=255

#
# An unspecified exit or interrupt should exit with ZONE_SUBPROC_NOTCOMPLETE,
# meaning a user will not need to do an uninstall before attempting another
# install.
#
int_code=$ZONE_SUBPROC_NOTCOMPLETE

trap trap_cleanup INT

# If we weren't passed at least two arguments, exit now.
[[ $# -lt 2 ]] && usage

#
# This script is always started with a full path so we can extract the
# brand directory name here.
#
branddir=$(dirname "$0")
zonename="$1"
zoneroot="$2"

install_root="$zoneroot/root"
logdir="$install_root/var/log"

shift; shift	# remove zonename and zoneroot from arguments array

unset gtaropts
unset install_opts
unset install_src
unset msg
unset silent_mode
unset verbose_mode

while getopts "d:hsvX" opt
do
	case "$opt" in
		h) 	usage;;
		s)	silent_mode=1;;
		v)	verbose_mode=1;;
		d) 	install_src="$OPTARG" ;;
		X)	install_opts="$install_opts -x" ;;
		*)	usage;;
	esac
done
shift OPTIND-1

if [[ $# -gt 0 ]]; then
	msg="ERROR: Too many arguments provided:"

	screenlog "$msg"
	screenlog "  \"%s\"" "$@"
	screenlog ""
	usage
fi

# The install can't be both verbose AND silent...
if [[ -n $silent_mode && -n $verbose_mode ]]; then
	screenlog "$both_modes" "zoneadm install"
	screenlog ""
	usage
fi

# Install tarball is required
if [[ -z $install_src ]]; then
	msg="ERROR: the install archive is required"

	screenlog "$msg"
	screenlog ""
	usage
fi

#
# Validate $install_src.
#
if [[ "`echo $install_src | cut -c 1`" != "/" ]]; then
	screenlog "$path_abs" "$install_src"
	exit $int_code
fi

if [[ ! -a "$install_src" ]]; then
	screenlog "$not_found" "$install_src"
	screenlog "$install_abort" "$zonename"
	exit $int_code
fi

if [[ ! -r "$install_src" ]]; then
	screenlog "$not_readable" "$install_src"
	screenlog "$install_abort" "$zonename"
	exit $int_code
fi

if [[ ! -f "$install_src" ]]; then
	screenlog "$wrong_type" "$install_src"
	screenlog "$install_abort" "$zonename"
	exit $int_code
fi

filetype=`{ LC_ALL=C file $install_src | awk '{print $2}' ; } 2>/dev/null`

if [[ "$filetype" = "gzip" ]]; then
	verbose "\"$install_src\": \"gzip\" archive"
	gtaropts="-xz"
elif [[ "$filetype" = "bzip2" ]]; then
	verbose "\"$install_src\": \"bzip2\" archive"
	gtaropts="-xj"
elif [[ "$filetype" = "compressed" ]]; then
	verbose "\"$install_src\": Lempel-Ziv" "compressed (\".Z\") archive."
	gtaropts="-xZ"
elif [[ "$filetype" = "USTAR" ]]; then
	verbose "\"$install_src\":" "uncompressed (\"tar\") archive."
	gtaropts="-x"
else
	screenlog "$wrong_type" "$install_src"
	screenlog "$install_abort" "$zonename"
	exit $int_code
fi

#
# Start silent operation
#
if [[ -n $silent_mode ]]; then
	exec 1>/dev/null
	install_opts="$install_opts -s"
fi

if [[ -n $verbose_mode ]]; then
	echo $(gettext "Verbose output mode enabled.")
	install_opts="$install_opts -v"
	[[ -n $gtaropts ]] && gtaropts="${gtaropts}v"
fi

gtaropts="${gtaropts}f"

if [[ ! -d "$install_root" ]]; then
	if ! mkdir -p "$install_root" 2>/dev/null; then
		screenlog "$no_install" "$install_root"
		exit $int_code
	fi
fi

#
# Check for a non-empty root.
# 
cnt=`ls $install_root | wc -l`
if [ $cnt -ne 0 ]; then
	screenlog "$root_full" "$install_root"
	exit $int_code
fi

if [[ ! -d "$logdir" ]]; then
	if ! mkdir -p "$logdir" 2>/dev/null; then
		screenlog "$no_log" "$logdir"
		exit $int_code
	fi
fi

logfile="${logdir}/$zonename.install.$$.log"

if ! > $logfile; then
	screenlog "$no_logfile" "$logfile"
	exit $int_code
fi

# Redirect stderr to the log file to automatically log any error messages
exec 2>>"$logfile"

#
# From here on out, an unspecified exit or interrupt should exit with
# ZONE_SUBPROC_FATAL, meaning a user will need to do an uninstall before
# attempting another install, as we've modified the directories we were going
# to install to in some way.
#
int_code=$ZONE_SUBPROC_FATAL

log "Installation started for zone \"$zonename\" `/usr/bin/date`"

screenlog "$install_zone" "$zonename" "$zoneroot"
screenlog "$install_from" "$install_src"
echo
echo $(gettext "This process may take several minutes.")
echo

if ! ( cd "$install_root" && gtar "$gtaropts" "$install_src" ) ; then
	log "Error: extraction from tar archive failed."
else
	if ! [[ -d "${install_root}/bin" &&
	    -d "${install_root}/sbin" ]]; then
		log "Error: improper or incomplete tar archive."
	else
		$branddir/lx_init_zone "$install_root"

		#
		# Emit the same code from here whether we're
		# interrupted or exiting normally.
		#
		int_code=$?
	fi
fi

mkdir $zoneroot/cores

if [[ $int_code -eq ZONE_SUBPROC_OK ]]; then
	log "Install completed for zone '$zonename' `date`."
else
	log "Install failed for zone \"$zonename\" `date`."
fi

if [[ $int_code -ne $ZONE_SUBPROC_OK ]]; then
	screenlog ""
	screenlog "$install_fail" "$zonename"
	screenlog ""

	#
	# Only make a reference to the log file if one will exist after
	# zoneadm exits.
	#
	[[ $int_code -ne $ZONE_SUBPROC_NOTCOMPLETE ]] &&
	    screenlog "$see_log" "$logfile"

	exit $int_code
fi

#
# After the install completes, we've likely moved a new copy of the logfile into
# place atop the logfile we WERE writing to, so if we don't reopen the logfile
# here the shell will continue writing to the old logfile's inode, meaning we
# would lose all log information from this point on.
#
exec 2>>"$logfile"

screenlog ""
screenlog "$install_good" "$zonename"
screenlog ""

echo $(gettext "Details saved to log file:")
echo "    \"$logfile\""
echo

exit $ZONE_SUBPROC_OK
