#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident "%Z%%M% %I% %E% SMI"

. /lib/svc/share/smf_include.sh
. /lib/svc/share/net_include.sh

set -o xtrace

# Make sure that the libraries essential to this stage of booting can be found.
LD_LIBRARY_PATH=/lib; export LD_LIBRARY_PATH

#
# If DHCP was used on a primary interface then set the hostname
# that was returned. If no hostname was returned, set the name
# to be "unknown". The hostname must be set to something, because
# tooltalk will hang unless the name can be locally resolved.
# Sendmail also requires the name to be resolvable locally.
# Later, in inetsvc, we create a name "unknown" and create a entry
# in the local /etc/inet/hosts file pairing "unknown" with the IP
# address assigned by DHCP.  The use of bootparams as a fallback
# for all non-DHCP cases provides compatibility with the
# behavior of the system before netstrategy was introduced.
#
# For non-global zones, fall back to the `uname -n` value provided by the
# kernel if /etc/nodename does not exist, as is expected on an initial boot.
#

smf_netstrategy

case "$_INIT_NET_STRATEGY" in
    "dhcp") hostname=`/sbin/dhcpinfo Hostname` ;;
    "rarp") hostname=`/sbin/hostconfig -h -p bootparams`
        trap 'intr=1' 2 3
        while [ -z "$hostname" -a ! -f /etc/.UNCONFIGURED -a \
            -z "$intr" ]; do
            echo "re-trying host configuration..."
            # Restrict this to IPv4 interfaces.
            /sbin/ifconfig -adD4 auto-revarp up
            hostname=`/sbin/hostconfig -h -p bootparams`
        done
        trap 2 3 ;;
    "none") hostname="`shcat /etc/nodename 2>/dev/null`"
            if [ -z "$hostname" ]; then
            if smf_is_globalzone; then
                hostname=`/sbin/hostconfig -h -p bootparams`
            else
                hostname=`/sbin/uname -n`
            fi
        fi ;;
esac

# Load sysinfo variables with SYSINFO_ prefix
eval $(/usr/bin/sysinfo -p | sed -e "s/^/SYSINFO_/")
if [[ -n ${SYSINFO_NIC_admin} ]]; then
    eval "admin_mac=\${SYSINFO_Network_Interface_${SYSINFO_NIC_admin}_MAC_Address}"
fi
if [[ -z ${admin_mac} ]]; then
    fallback_mac=$(set | grep "^SYSINFO_Network_Interface_.*_MAC_Address" | head -n1 | cut -d'=' -f2)
fi

#
# If the netstrategy was unsuccessful and we haven't got a locally configured
# name, default to "unknown"
#
if [ -z "$hostname" ] || [ "$hostname" == "unknown" ]; then
    hostname="`shcat /etc/nodename 2>/dev/null`"
    if [ -z "$hostname" ] || [ "$hostname" == "unknown" ]; then
        if smf_is_globalzone && [ -n "$(bootparams | grep '^headnode=true')" ]; then
            configfile="$(svcprop -p 'joyentfs/usb_copy_path' svc:/system/filesystem/joyent:default)/config"
            if [[ ! -f ${configfile} ]]; then
                configfile="$(svcprop -p 'joyentfs/usb_mountpoint' svc:/system/filesystem/joyent:default)/config"
            fi
            hostname=$(grep '^hostname=' ${configfile} | cut -d'=' -f2-)
            if [[ -z ${hostname} ]]; then
                hostname="headnode"
            fi
        elif smf_is_globalzone; then
            # take admin nic as hostname
            if [[ -n ${admin_mac} ]]; then
                hostname=$(echo "${admin_mac}" | tr ':' '-')
            elif [[ -n ${fallback_mac} ]]; then
                hostname=$(echo "${fallback_mac}" | tr ':' '-')
            else
                hostname="unknown"
            fi
        else
            hostname="unknown"
        fi
    fi
fi

/sbin/uname -S $hostname

# Try to add the /etc/hosts entry if we can find an IP
if [[ -n ${SYSINFO_NIC_admin} ]]; then
    eval "ipaddr=\${SYSINFO_Network_Interface_${SYSINFO_NIC_admin}_IPv4_Address}"
fi
if [[ -z ${ipaddr} ]]; then
    ipaddr=$(set | grep "^SYSINFO_Network_Interface_.*_IPv4_Address" | head -n1 | cut -d'=' -f2)
fi
if [[ -n ${ipaddr} ]]; then
    printf "${ipaddr}\t${hostname}\n" >> /etc/hosts
fi

# Reset the library path now that we are past the critical stage
unset LD_LIBRARY_PATH

exit $SMF_EXIT_OK
